#!/usr/bin/env python3
"""Regenerate the SDK's pydantic v2 models from the committed OpenAPI contract.

    python scripts/generate_models.py

Reads the committed ``openapi.json`` (the snapshot of the public Goable API
contract) and emits pydantic v2 models via ``datamodel-code-generator`` into
``src/goable_sdk/_models.py``. This script does NOT touch ``openapi.json`` --
that file is refreshed from the live API by
``.github/workflows/refresh-openapi.yml``.

NEVER hand-edit ``src/goable_sdk/_models.py`` -- it is fully regenerated by
this script on every run. Requires the ``dev`` extra:

    pip install -e ".[dev]"
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

PKG_ROOT = Path(__file__).resolve().parent.parent
OPENAPI_JSON = PKG_ROOT / "openapi.json"
OUTPUT = PKG_ROOT / "src" / "goable_sdk" / "_models.py"

# Keep in sync with the invocation documented in README.md ("Types are
# generated from the API contract").
DATAMODEL_CODEGEN_ARGS = [
    "--input",
    str(OPENAPI_JSON),
    "--input-file-type",
    "openapi",
    "--output",
    str(OUTPUT),
    "--output-model-type",
    "pydantic_v2.BaseModel",
    "--target-python-version",
    "3.10",
    # Pull in per-path request/response schemas (not just components/schemas),
    # so every endpoint gets a named `V1<Path>PostRequest` / `...Response`
    # model instead of only the ~18 top-level shared schemas.
    "--openapi-scopes",
    "schemas",
    "paths",
    "parameters",
    "--use-schema-description",
    "--field-constraints",
    "--use-double-quotes",
    "--collapse-root-models",
]


def main() -> int:
    if not OPENAPI_JSON.exists():
        print(f"error: {OPENAPI_JSON} not found", file=sys.stderr)
        return 1

    print(f"[generate_models] datamodel-codegen -> {OUTPUT.relative_to(PKG_ROOT)}")
    result = subprocess.run(
        [sys.executable, "-m", "datamodel_code_generator", *DATAMODEL_CODEGEN_ARGS],
        cwd=PKG_ROOT,
        check=False,
    )
    if result.returncode != 0:
        return result.returncode

    # Normalise formatting to match the repo's ruff config (datamodel-code-generator
    # ships its own black/isort formatting pass, which can disagree with ours).
    for cmd in (["ruff", "format", str(OUTPUT)], ["ruff", "check", "--fix", str(OUTPUT)]):
        fmt = subprocess.run([sys.executable, "-m", *cmd], cwd=PKG_ROOT, check=False)
        if fmt.returncode != 0:
            print(f"[generate_models] warning: `{' '.join(cmd)}` exited {fmt.returncode}", file=sys.stderr)

    print("[generate_models] wrote src/goable_sdk/_models.py from openapi.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
