"""goable-sdk -- Python client for the Goable API.

    from goable_sdk import GoableClient

    goable = GoableClient(api_key=os.environ["GOABLE_API_KEY"])
    result = goable.score({
        "activity": "kitesurfing",
        "location": {"lat": 43.7, "lng": 7.27},
    })
    result.score     # 0-100
    result.verdict    # "unsafe" | "poor" | "marginal" | "fair" | "favorable" | "excellent"
    result.confidence

Mirrors ``/home/user/sdk/src/index.ts``: the client + error types + the
per-endpoint request/response models are all importable from the top-level
package. The full generated surface (every schema in the OpenAPI contract,
including nested/shared types not re-exported here by name) is available via
the ``goable_sdk.models`` submodule for advanced consumers, mirroring the TS
SDK's ``export type { components, paths } from "./generated/api.ts"``.
"""

from . import _models as models

# ── per-endpoint request/response models (generated), re-exported for
# convenient top-level import (e.g. `from goable_sdk import ScoreResponse`) ──
from ._models import (
    GeoPoint,
    ScoreMultiResponse,
    ScoreResponse,
    ScoreSeriesResponse,
    SerialisedPayoutEvent,
    SerialisedPolicy,
    TimeWindow,
    UnderwritingQuoteResponse,
    V1AuditExportGetParametersQuery,
    V1AuditExportGetResponse,
    V1DecisionPostRequest,
    V1DecisionPostResponse,
    V1HealthGetResponse,
    V1HealthReadyGetResponse,
    V1IntelligenceBriefingPostRequest,
    V1IntelligenceBriefingPostResponse,
    V1IntelligenceEdgeCasePostRequest,
    V1IntelligenceEdgeCasePostResponse,
    V1IntelligenceExplainPostRequest,
    V1IntelligenceExplainPostResponse,
    V1LegalKindCurrentGetResponse,
    V1ObservationsPostRequest,
    V1ObservationsPostResponse,
    V1ObservationsStationsGetResponse,
    V1ObservationsStationsPostRequest,
    V1ObservationsStationsPostResponse,
    V1ObservationsStationsStationIdPatchRequest,
    V1ObservationsStationsStationIdPatchResponse,
    V1ObservationsStationsStationIdRecentGetParametersQuery,
    V1ObservationsStationsStationIdRecentGetResponse,
    V1OutcomesPostRequest,
    V1OutcomesPostResponse,
    V1ProjectionsAdaptationReportPostRequest,
    V1ProjectionsAdaptationReportPostResponse,
    V1ProjectionsPortfolioPostRequest,
    V1ProjectionsPortfolioPostResponse,
    V1ProjectionsPostRequest,
    V1ProjectionsPostResponse,
    V1PublicCatalogStatsGetResponse,
    V1PublicSignupPostRequest,
    V1PublicSignupPostResponse,
    V1PublicSustainabilityIndexGetParametersQuery,
    V1PublicSustainabilityIndexGetResponse,
    V1RecommendSpotPostRequest,
    V1RecommendSpotPostResponse,
    V1ResearchVerificationExportGetParametersQuery,
    V1ScoreDifficultyPostRequest,
    V1ScoreDifficultyPostResponse,
    V1ScoreExplainCounterfactualPostRequest,
    V1ScoreExplainCounterfactualPostResponse,
    V1ScoreHistoricalPostRequest,
    V1ScoreHistoricalPostResponse,
    V1ScoreMultiPostRequest,
    V1ScorePortfolioPostRequest,
    V1ScorePortfolioPostResponse,
    V1ScorePostRequest,
    V1ScoreSeriesPostRequest,
    V1ScoreSessionIdOutcomePostRequest,
    V1ScoreSessionIdOutcomePostResponse,
    V1TenantLlmKeyGetResponse,
    V1TenantLlmKeyPutRequest,
    V1UnderwritingPolicyBindPostRequest,
    V1UnderwritingPolicyBindPostResponse,
    V1UnderwritingPolicyGetParametersQuery,
    V1UnderwritingPolicyGetResponse,
    V1UnderwritingPolicyPolicyIdEvaluatePostResponse,
    V1UnderwritingPolicyPolicyIdGetResponse,
    V1UnderwritingPolicyPolicyIdSettlePostRequest,
    V1UnderwritingPolicyPolicyIdSettlePostResponse,
    V1UnderwritingQuotePostRequest,
    Verdict,
    WebhookEvent,
)
from .client import (
    DEFAULT_BASE_URL,
    DEFAULT_TIMEOUT_S,
    DeleteUserDataResult,
    GoableClient,
    LegalDocumentKind,
    RequestBody,
    WebhookDelivery,
)
from .errors import (
    DriftActiveError,
    GoableAPIError,
    GoableNetworkError,
    HeaderBag,
    RateLimit,
    ZodIssueLike,
)

__version__ = "0.1.0"

__all__ = [
    "DEFAULT_BASE_URL",
    "DEFAULT_TIMEOUT_S",
    "DeleteUserDataResult",
    "DriftActiveError",
    "GeoPoint",
    "GoableAPIError",
    "GoableClient",
    "GoableNetworkError",
    "HeaderBag",
    "LegalDocumentKind",
    "RateLimit",
    "RequestBody",
    "ScoreMultiResponse",
    "ScoreResponse",
    "ScoreSeriesResponse",
    "SerialisedPayoutEvent",
    "SerialisedPolicy",
    "TimeWindow",
    "UnderwritingQuoteResponse",
    "V1AuditExportGetParametersQuery",
    "V1AuditExportGetResponse",
    "V1DecisionPostRequest",
    "V1DecisionPostResponse",
    "V1HealthGetResponse",
    "V1HealthReadyGetResponse",
    "V1IntelligenceBriefingPostRequest",
    "V1IntelligenceBriefingPostResponse",
    "V1IntelligenceEdgeCasePostRequest",
    "V1IntelligenceEdgeCasePostResponse",
    "V1IntelligenceExplainPostRequest",
    "V1IntelligenceExplainPostResponse",
    "V1LegalKindCurrentGetResponse",
    "V1ObservationsPostRequest",
    "V1ObservationsPostResponse",
    "V1ObservationsStationsGetResponse",
    "V1ObservationsStationsPostRequest",
    "V1ObservationsStationsPostResponse",
    "V1ObservationsStationsStationIdPatchRequest",
    "V1ObservationsStationsStationIdPatchResponse",
    "V1ObservationsStationsStationIdRecentGetParametersQuery",
    "V1ObservationsStationsStationIdRecentGetResponse",
    "V1OutcomesPostRequest",
    "V1OutcomesPostResponse",
    "V1ProjectionsAdaptationReportPostRequest",
    "V1ProjectionsAdaptationReportPostResponse",
    "V1ProjectionsPortfolioPostRequest",
    "V1ProjectionsPortfolioPostResponse",
    "V1ProjectionsPostRequest",
    "V1ProjectionsPostResponse",
    "V1PublicCatalogStatsGetResponse",
    "V1PublicSignupPostRequest",
    "V1PublicSignupPostResponse",
    "V1PublicSustainabilityIndexGetParametersQuery",
    "V1PublicSustainabilityIndexGetResponse",
    "V1RecommendSpotPostRequest",
    "V1RecommendSpotPostResponse",
    "V1ResearchVerificationExportGetParametersQuery",
    "V1ScoreDifficultyPostRequest",
    "V1ScoreDifficultyPostResponse",
    "V1ScoreExplainCounterfactualPostRequest",
    "V1ScoreExplainCounterfactualPostResponse",
    "V1ScoreHistoricalPostRequest",
    "V1ScoreHistoricalPostResponse",
    "V1ScoreMultiPostRequest",
    "V1ScorePortfolioPostRequest",
    "V1ScorePortfolioPostResponse",
    "V1ScorePostRequest",
    "V1ScoreSeriesPostRequest",
    "V1ScoreSessionIdOutcomePostRequest",
    "V1ScoreSessionIdOutcomePostResponse",
    "V1TenantLlmKeyGetResponse",
    "V1TenantLlmKeyPutRequest",
    "V1UnderwritingPolicyBindPostRequest",
    "V1UnderwritingPolicyBindPostResponse",
    "V1UnderwritingPolicyGetParametersQuery",
    "V1UnderwritingPolicyGetResponse",
    "V1UnderwritingPolicyPolicyIdEvaluatePostResponse",
    "V1UnderwritingPolicyPolicyIdGetResponse",
    "V1UnderwritingPolicyPolicyIdSettlePostRequest",
    "V1UnderwritingPolicyPolicyIdSettlePostResponse",
    "V1UnderwritingQuotePostRequest",
    "Verdict",
    "WebhookDelivery",
    "WebhookEvent",
    "ZodIssueLike",
    "__version__",
    "models",
]
