# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-07-14T22:33:19+00:00

from __future__ import annotations

from enum import Enum, IntEnum
from typing import Any, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, EmailStr, Field, RootModel


class GeoPoint(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    lat: float = Field(..., examples=[36.0133])
    lng: float = Field(..., examples=[-5.6044])


class TimeWindow(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    from_: AwareDatetime = Field(..., alias="from")
    to: AwareDatetime


class Error(BaseModel):
    error: str = Field(..., description="Machine-readable error code")
    message: str | None = None
    issues: list[dict[str, Any]] | None = None
    detail: dict[str, Any] | None = None


class Verdict(Enum):
    unsafe = "unsafe"
    poor = "poor"
    marginal = "marginal"
    fair = "fair"
    favorable = "favorable"
    excellent = "excellent"


class BreakdownItem(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    name: str | None = None
    value: float | None = None
    suitability: float | None = None
    weight: float | None = None
    contribution: float | None = None
    hasData: bool | None = None


class Level(Enum):
    info = "info"
    warning = "warning"
    critical = "critical"


class Alert(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    level: Level | None = None
    code: str | None = None
    description: str | None = None


class Series(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    at: AwareDatetime | None = None
    score: float
    verdict: Verdict


class ScoreSeriesResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    series: list[Series]


class Result(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    activity: str
    score: float
    verdict: Verdict


class ScoreMultiResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    results: list[Result]


class Level1(Enum):
    sub_spot = "sub-spot"
    cluster = "cluster"
    region = "region"
    base = "base"


class Tier(IntEnum):
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3


class TierSource(Enum):
    catalog = "catalog"
    classifier = "classifier"


class CalibrationProvenance(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    level: Level1 | None = None
    slug: str | None = None
    scoring_profile_slug: str | None = None
    sub_spot_slug: str | None = None
    distance_to_sub_spot_m: float | None = None
    tier: Tier | None = None
    tier_source: TierSource | None = None


class Level2(Enum):
    base = "base"
    region = "region"
    cluster = "cluster"
    sub_spot = "sub-spot"


class CalibrationProvenanceSummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    level: Level2
    n_local: int | None
    shrinkage_weight_from_parent: float | None = Field(..., ge=0.0, le=1.0)


class Severity(Enum):
    watch = "watch"
    warning = "warning"
    critical = "critical"


class DriftFlag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    severity: Severity
    since_timestamp: AwareDatetime


class Mode(Enum):
    forecast = "forecast"


class SkillCalibration(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    applied: bool
    n_train: int
    cohort_hash: str
    scalar: float = Field(..., ge=0.85, le=1.0)


class ConfidenceDetailForecast(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    mode: Literal["forecast"]
    forecast_skill: float = Field(..., ge=0.0, le=1.0)
    provider_agreement: float = Field(..., ge=0.0, le=1.0)
    profile_maturity: float = Field(..., ge=0.0, le=1.0)
    hierarchical_calibration: float = Field(..., ge=0.0, le=1.0)
    calibration_provenance: CalibrationProvenanceSummary | None = None
    skill_calibration: SkillCalibration | None = None
    drift_flag: DriftFlag | None = None


class Mode1(Enum):
    historical = "historical"


class ConfidenceDetailHistorical(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    mode: Literal["historical"]
    sample_size_confidence: float = Field(..., ge=0.0, le=1.0)
    base_climatology_quality: float = Field(..., ge=0.0, le=1.0)
    calibration_confidence: float = Field(..., ge=0.0, le=1.0)
    hierarchical_calibration: float = Field(..., ge=0.0, le=1.0)
    calibration_provenance: CalibrationProvenanceSummary | None = None
    drift_flag: DriftFlag | None = None


class Mode2(Enum):
    climate = "climate"


class ConfidenceDetailClimate(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    mode: Literal["climate"]
    model_spread: float = Field(..., ge=0.0, le=1.0)
    bias_correction_residual: float = Field(..., ge=0.0, le=1.0)
    scenario_uncertainty: float = Field(..., ge=0.0, le=1.0)
    horizon_uncertainty: float = Field(..., ge=0.0, le=1.0)
    hierarchical_calibration: float = Field(..., ge=0.0, le=1.0)
    calibration_provenance: CalibrationProvenanceSummary | None = None
    drift_flag: DriftFlag | None = None


class Status(Enum):
    bound = "bound"
    triggered = "triggered"
    settled = "settled"
    expired = "expired"


class PayoutCurrency(Enum):
    EUR = "EUR"
    USD = "USD"
    GBP = "GBP"
    CHF = "CHF"


class PremiumCollection(Enum):
    external = "external"
    stripe = "stripe"
    invoice_due = "invoice_due"


class CoverageWindow(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    monthFrom: int = Field(..., ge=1, le=12)
    dayFrom: int = Field(..., ge=1, le=31)
    monthTo: int = Field(..., ge=1, le=12)
    dayTo: int = Field(..., ge=1, le=31)


class SerialisedPolicy(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID
    tenantId: UUID
    quoteId: UUID
    status: Status
    payoutAmount: float | None = Field(
        None,
        description="Null for mixed-currency portfolios; the breakdown lives on the underlying quote.",
    )
    payoutCurrency: PayoutCurrency | None = None
    premiumPaid: float | None = None
    premiumCollection: PremiumCollection
    coverageWindow: CoverageWindow
    coverageYear: int = Field(..., ge=2000, le=2100)
    trigger: dict[str, Any] = Field(
        ...,
        description="Frozen at bind time — same shape as the quote's normalised trigger.",
    )
    policyTerms: dict[str, Any] = Field(
        ...,
        description="Frozen snapshot of the per-spot profile + payout terms — decouples the policy from later catalog changes.",
    )
    boundAt: AwareDatetime
    triggeredAt: AwareDatetime | None
    settledAt: AwareDatetime | None
    expiredAt: AwareDatetime | None
    settlementReference: str | None


class EvaluationSource(Enum):
    manual = "manual"
    scheduled = "scheduled"


class SerialisedPayoutEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID
    policyId: UUID
    spotIndex: int = Field(..., ge=0)
    eventStartAt: AwareDatetime
    eventEndAt: AwareDatetime
    hoursFired: float
    payoutAmount: float
    payoutCurrency: PayoutCurrency
    detectedAt: AwareDatetime
    evaluationSource: EvaluationSource


class HistoricalYearsRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    from_: int = Field(..., alias="from")
    to: int


class Currency(Enum):
    EUR = "EUR"
    USD = "USD"
    GBP = "GBP"
    CHF = "CHF"


class Payout(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    amount: float = Field(..., gt=0.0)
    currency: Currency


class Tier1(Enum):
    """
    Sub-spot tier (1/2/3) applied to the tier risk multiplier; null when no sub-spot resolved.
    """

    int_1 = 1
    int_2 = 2
    int_3 = 3
    NoneType_None = None


class TierSource1(Enum):
    """
    Provenance of the tier: 'catalog' from profile YAML, 'classifier' from L11 confidence=1.0 override, null when no tier applied.
    """

    catalog = "catalog"
    classifier = "classifier"
    NoneType_None = None


class Spot(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resolvedProfileSlug: str
    point: GeoPoint
    spotId: str | None = None
    payout: Payout
    tier: Tier1 | None = Field(
        None,
        description="Sub-spot tier (1/2/3) applied to the tier risk multiplier; null when no sub-spot resolved.",
    )
    tierSource: TierSource1 | None = Field(
        None,
        description="Provenance of the tier: 'catalog' from profile YAML, 'classifier' from L11 confidence=1.0 override, null when no tier applied.",
    )


class Payout1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    amount: float = Field(..., gt=0.0)
    currency: Currency


class PortfolioItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resolvedProfileSlug: str
    point: GeoPoint
    spotId: str | None = None
    payout: Payout1
    tier: Tier1 | None = Field(
        None,
        description="Sub-spot tier (1/2/3) applied to the tier risk multiplier; null when no sub-spot resolved.",
    )
    tierSource: TierSource1 | None = Field(
        None,
        description="Provenance of the tier: 'catalog' from profile YAML, 'classifier' from L11 confidence=1.0 override, null when no tier applied.",
    )


class Policy(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    coverageWindow: CoverageWindow
    trigger: dict[str, Any] = Field(
        ...,
        description="Normalised trigger echoed back with defaulted consecutiveHours/cooldownHours.",
    )
    historicalYearsRange: HistoricalYearsRange
    spot: Spot | None = None
    portfolio: list[PortfolioItem] | None = None


class EUR(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    mean: float
    p10: float
    p50: float
    p90: float
    perYear: list[float]
    varianceStability: float = Field(..., ge=0.0, le=1.0)


class USD(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    mean: float
    p10: float
    p50: float
    p90: float
    perYear: list[float]
    varianceStability: float = Field(..., ge=0.0, le=1.0)


class GBP(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    mean: float
    p10: float
    p50: float
    p90: float
    perYear: list[float]
    varianceStability: float = Field(..., ge=0.0, le=1.0)


class CHF(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    mean: float
    p10: float
    p50: float
    p90: float
    perYear: list[float]
    varianceStability: float = Field(..., ge=0.0, le=1.0)


class ByCurrency(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    EUR_1: EUR | None = Field(None, alias="EUR")
    USD_1: USD | None = Field(None, alias="USD")
    GBP_1: GBP | None = Field(None, alias="GBP")
    CHF_1: CHF | None = Field(None, alias="CHF")


class ExpectedPayouts(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    byCurrency: ByCurrency


class EUR1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    fair: float
    loaded: float
    tierMultiplierWeightedAvg: float = Field(
        ...,
        description="Weighted-average tier risk multiplier applied across spots in this currency (1.0 when no sub-spot).",
    )


class USD1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    fair: float
    loaded: float
    tierMultiplierWeightedAvg: float = Field(
        ...,
        description="Weighted-average tier risk multiplier applied across spots in this currency (1.0 when no sub-spot).",
    )


class GBP1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    fair: float
    loaded: float
    tierMultiplierWeightedAvg: float = Field(
        ...,
        description="Weighted-average tier risk multiplier applied across spots in this currency (1.0 when no sub-spot).",
    )


class CHF1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    fair: float
    loaded: float
    tierMultiplierWeightedAvg: float = Field(
        ...,
        description="Weighted-average tier risk multiplier applied across spots in this currency (1.0 when no sub-spot).",
    )


class ByCurrency1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    EUR: EUR1 | None = None
    USD: USD1 | None = None
    GBP: GBP1 | None = None
    CHF: CHF1 | None = None


class ExpectedPremium(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    byCurrency: ByCurrency1
    loadingFactor: float = Field(..., ge=0.0, le=2.0)


class AdvisoryLevel(Enum):
    high_confidence = "high_confidence"
    moderate_confidence = "moderate_confidence"
    low_confidence = "low_confidence"


class UnderwritingQuoteResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    policy: Policy
    expectedPayouts: ExpectedPayouts
    expectedPremium: ExpectedPremium
    modelConfidence: float = Field(..., ge=0.0, le=1.0)
    advisoryLevel: AdvisoryLevel
    issuable: bool
    notes: list[str]
    underlying: dict[str, Any] | list[dict[str, Any]] = Field(
        ...,
        description="HistoricalScoreDistribution — object for single spot, array for portfolio.",
    )
    quoteId: UUID | None = Field(
        None,
        description="Present when the policy store is wired — pass to /v1/underwriting/policy/bind to bind this quote.",
    )
    expiresAt: AwareDatetime | None = Field(
        None, description="ISO timestamp after which the quote can no longer be bound."
    )
    boundPolicyId: UUID | None = Field(
        None,
        description="Present on GET after the quote has been bound — the resulting policy id.",
    )


class WebhookEvent(Enum):
    outcome_created = "outcome.created"
    drift_fired = "drift.fired"
    drift_resolved = "drift.resolved"
    calibration_completed = "calibration.completed"
    billing_subscription_updated = "billing.subscription_updated"
    recommendation_completed = "recommendation.completed"
    underwriting_policy_bound = "underwriting.policy.bound"
    underwriting_policy_triggered = "underwriting.policy.triggered"
    underwriting_policy_settled = "underwriting.policy.settled"


class V1HealthGetResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class V1HealthReadyGetResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class RiderSkillLevel(Enum):
    """
    Skill-conditioned scoring (Pro+).
    """

    beginner = "beginner"
    intermediate = "intermediate"
    expert = "expert"


class V1ScorePostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    activity: str = Field(..., examples=["kitesurfing"])
    location: GeoPoint
    window: TimeWindow | None = None
    ensemble: bool | None = Field(None, description="L2a probabilistic ensemble (Pro+)")
    members: int | None = Field(None, ge=2, le=50)
    rider_skill_level: RiderSkillLevel | None = Field(None, description="Skill-conditioned scoring (Pro+).")


class Granularity(Enum):
    hourly = "hourly"
    field_3_hourly = "3-hourly"
    daily = "daily"


class V1ScoreSeriesPostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    activity: str
    location: GeoPoint
    window: TimeWindow
    granularity: Granularity | None = None
    ensemble: bool | None = None
    members: int | None = Field(None, ge=2, le=50)


class V1ScoreMultiPostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    activities: list[str] = Field(..., max_length=10, min_length=1)
    location: GeoPoint
    window: TimeWindow | None = None
    ensemble: bool | None = None
    members: int | None = Field(None, ge=2, le=50)


class YearsRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    from_: int = Field(..., alias="from", ge=1940)
    to: int


class Granularity1(Enum):
    month = "month"
    week = "week"
    day_of_year = "day-of-year"
    daypart = "daypart"


class Daypart(Enum):
    morning = "morning"
    midday = "midday"
    afternoon = "afternoon"
    evening = "evening"


class Selector(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    month: int | None = Field(None, ge=1, le=12)
    weekOfYear: int | None = Field(None, ge=1, le=53)
    dayOfYear: int | None = Field(None, ge=1, le=366)
    daypart: Daypart | None = None


class V1ScoreHistoricalPostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    activity: str
    location: GeoPoint
    yearsRange: YearsRange
    granularity: Granularity1
    selector: Selector
    failOnMarineGap: bool | None = None


class V1ScoreHistoricalPostResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class Spot1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    location: GeoPoint
    activity: str
    weight: float | None = Field(None, gt=0.0)
    spotId: str | None = None


class Selector1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    month: int | None = Field(None, ge=1, le=12)
    weekOfYear: int | None = Field(None, ge=1, le=53)
    dayOfYear: int | None = Field(None, ge=1, le=366)
    daypart: Daypart | None = None


class Model(Enum):
    none = "none"
    exponential = "exponential"


class Correlation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    model: Model | None = None
    lengthKm: float | None = Field(None, gt=0.0)


class V1ScorePortfolioPostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    spots: list[Spot1] = Field(..., max_length=50, min_length=1)
    yearsRange: YearsRange
    granularity: Granularity1
    selector: Selector1
    correlation: Correlation | None = None
    cancellationThreshold: float | None = Field(None, ge=0.0, le=100.0)


class V1ScorePortfolioPostResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class Include(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    marginal_sensitivities: bool | None = None
    binding_constraint: bool | None = None
    best_window_24h: bool | None = None
    best_nearby_spot_km: float | None = Field(None, le=200.0)
    natural_language: bool | None = Field(
        None,
        description="LLM explanation. Available on any plan (Anthropic BYOK) — resolves the tenant's own Anthropic key set via PUT /v1/tenant/llm-key; no key configured degrades to a deterministic template (natural_language.degraded_mode=true) rather than an error.",
    )


class V1ScoreExplainCounterfactualPostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    activity: str = Field(..., max_length=64)
    spot: GeoPoint
    window: TimeWindow
    include: Include | None = None


class V1ScoreExplainCounterfactualPostResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class Experience(Enum):
    beginner = "beginner"
    intermediate = "intermediate"
    advanced = "advanced"
    expert = "expert"


class RiskTolerance(Enum):
    conservative = "conservative"
    moderate = "moderate"
    aggressive = "aggressive"


class OwnedGearItem(RootModel[str]):
    root: str = Field(..., max_length=64)


class UserProfile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    experience: Experience | None = None
    weight_kg: float | None = Field(None, gt=0.0, le=300.0)
    risk_tolerance: RiskTolerance | None = None
    owned_gear: list[OwnedGearItem] | None = Field(None, max_length=20)


class V1DecisionPostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    user_pseudonym: str = Field(
        ...,
        description="SHA256(user_id + secret)[:32], hex ≥32 chars. NEVER PII.",
        min_length=32,
        pattern="^[0-9a-fA-F]+$",
    )
    activity: str = Field(..., max_length=64)
    spot: GeoPoint
    window: TimeWindow
    user_profile: UserProfile | None = None
    training_consent: bool | None = False


class V1DecisionPostResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class Locale(Enum):
    en = "en"
    it = "it"


class Model1(Enum):
    claude_haiku_4_5_20251001 = "claude-haiku-4-5-20251001"
    claude_sonnet_4_6 = "claude-sonnet-4-6"


class V1IntelligenceExplainPostResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class V1IntelligenceBriefingPostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    activity: str
    slots: list[dict[str, Any]]
    locale: Locale | None = None
    model: Model1 | None = None


class V1IntelligenceBriefingPostResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class V1TenantLlmKeyPutRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    apiKey: str = Field(
        ...,
        description="The tenant's own Anthropic API key (sk-ant-...).",
        max_length=300,
        min_length=20,
    )


class V1TenantLlmKeyGetResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    set: bool
    last4: str | None = None
    setAt: AwareDatetime | None = None
    lastValidatedAt: AwareDatetime | None = None


class Spot2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    location: GeoPoint
    activity: str
    spotId: str | None = None


class Scenario(Enum):
    SSP1_2_6 = "SSP1-2.6"
    SSP2_4_5 = "SSP2-4.5"
    SSP3_7_0 = "SSP3-7.0"
    SSP5_8_5 = "SSP5-8.5"


class BaselineDecade(Enum):
    field_2020s = "2020s"
    field_2030s = "2030s"


class V1ProjectionsPostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    spot: Spot2
    scenarios: list[Scenario] = Field(..., min_length=1)
    horizonDecades: list[str] | None = None
    baselineDecade: BaselineDecade | None = None


class V1ProjectionsPostResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class Payout2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    amount: float = Field(..., gt=0.0)
    currency: Currency


class Spot3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    point: GeoPoint
    activity: str = Field(..., min_length=1)
    spotId: str | None = None
    payout: Payout2


class Payout3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    amount: float = Field(..., gt=0.0)
    currency: Currency


class PortfolioItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    point: GeoPoint
    activity: str = Field(..., min_length=1)
    spotId: str | None = None
    payout: Payout3


class Kind(Enum):
    scoreBelow = "scoreBelow"


class Trigger(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Kind
    scoreBelow: float = Field(..., ge=0.0, le=100.0)
    consecutiveHours: int | None = Field(None, ge=1, le=72)
    cooldownHours: int | None = Field(None, ge=0, le=168)
    maxPayoutsPerYear: int | None = Field(None, ge=1)


class Kind1(Enum):
    verdictAtOrBelow = "verdictAtOrBelow"


class Trigger1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Kind1
    verdict: Verdict
    consecutiveHours: int | None = Field(None, ge=1, le=72)
    cooldownHours: int | None = Field(None, ge=0, le=168)
    maxPayoutsPerYear: int | None = Field(None, ge=1)


class HistoricalYearsRange1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    from_: int = Field(..., alias="from", ge=1940)
    to: int


class V1UnderwritingQuotePostRequest(BaseModel):
    """
    Provide exactly one of spot or portfolio.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    spot: Spot3 | None = None
    portfolio: list[PortfolioItem1] | None = Field(None, max_length=50, min_length=2)
    coverageWindow: CoverageWindow
    trigger: Trigger | Trigger1
    historicalYearsRange: HistoricalYearsRange1 | None = None
    loadingFactor: float | None = Field(None, ge=0.0, le=2.0)
    calibrationConfidenceMin: float | None = Field(None, ge=0.0, le=1.0)
    forceIssue: bool | None = None


class V1UnderwritingPolicyBindPostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    quoteId: UUID
    coverageYear: int = Field(..., ge=2000, le=2100)
    premiumCollection: PremiumCollection
    premiumPaid: float | None = Field(None, ge=0.0)


class Severity1(Enum):
    watch = "watch"


class DriftAdvisory(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    spotIndex: int = Field(..., ge=0)
    activity: str
    subSpotSlug: str
    severity: Severity1
    since: AwareDatetime


class V1UnderwritingPolicyBindPostResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    policy: SerialisedPolicy
    quoteId: UUID
    driftAdvisories: list[DriftAdvisory] | None = Field(
        None,
        description="Soft warnings for cells with an open watch-level L9 drift event. Present only when non-empty.",
    )


class V1UnderwritingPolicyGetParametersQuery(BaseModel):
    status: Status | None = None
    coverageYear: int | None = Field(None, ge=2000, le=2100)
    limit: int | None = Field(None, ge=1, le=200)
    cursor: UUID | None = None


class V1UnderwritingPolicyGetResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    policies: list[SerialisedPolicy]


class V1UnderwritingPolicyPolicyIdGetResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    policy: SerialisedPolicy
    events: list[SerialisedPayoutEvent]


class V1UnderwritingPolicyPolicyIdEvaluatePostResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    policy: SerialisedPolicy
    events: list[SerialisedPayoutEvent]
    inserted: int = Field(..., ge=0)
    skipped: int = Field(..., ge=0)


class V1UnderwritingPolicyPolicyIdSettlePostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    settlementReference: str = Field(..., max_length=256, min_length=1)
    settledAt: AwareDatetime | None = None


class V1UnderwritingPolicyPolicyIdSettlePostResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    policy: SerialisedPolicy


class OutcomeType(Enum):
    ran = "ran"
    cancelled = "cancelled"
    rescheduled = "rescheduled"
    no_show = "no_show"
    note = "note"


class V1ScoreSessionIdOutcomePostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    outcome_type: OutcomeType
    detail: dict[str, Any] | None = None


class V1ScoreSessionIdOutcomePostResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class V1ScoreDifficultyPostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    activity: str = Field(..., min_length=1)
    location: GeoPoint


class Level3(Enum):
    sub_spot = "sub-spot"
    cluster = "cluster"
    region = "region"
    base = "base"


class Resolved(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    level: Level3
    slug: str
    sub_spot_slug: str | None = None
    distance_to_sub_spot_m: float | None = None


class Dimension(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    dimension: str
    grid: list[float]
    difficulty: list[float]
    discrimination_a: float
    cohort_hash: str
    computed_at: AwareDatetime


class V1ScoreDifficultyPostResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resolved: Resolved
    dimensions: list[Dimension]


class V1RecommendSpotPostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    activity: str = Field(..., min_length=1)
    regionCenter: GeoPoint
    radiusKm: float = Field(..., gt=0.0)
    topK: int = Field(..., ge=1)
    window: TimeWindow | None = None
    userPseudonym: str | None = Field(
        None,
        description="Optional booking-platform-side pseudonym. When present, Pro+ tenants get personalization via the L6 cold-start blend (cap 0.5 weight).",
        max_length=128,
        min_length=1,
    )


class Result1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    spotSlug: str | None = None
    name: str | None = None
    location: GeoPoint | None = None
    distanceKm: float | None = None
    score: float | None = None
    effectiveScore: float | None = None
    verdict: str | None = None
    personalScore: float | None = None
    personalWeight: float | None = None
    rank: int | None = None


class Status2(Enum):
    no_subspots_in_radius = "no_subspots_in_radius"


class NearestSubSpot(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    slug: str
    name: str
    distanceKm: float


class SuggestedAction(Enum):
    expand_radius = "expand_radius"


class Coverage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: Status2
    nearestSubSpot: NearestSubSpot
    suggestedAction: SuggestedAction
    suggestedRadiusKm: float


class Status3(Enum):
    no_subspots_for_activity = "no_subspots_for_activity"


class SuggestedAction1(Enum):
    request_coverage = "request_coverage"


class Coverage1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: Status3
    suggestedAction: SuggestedAction1


class V1RecommendSpotPostResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    results: list[Result1] | None = None
    allGated: bool | None = None
    totalCandidates: int | None = None
    rankedCandidates: int | None = None
    effectiveRadiusKm: float | None = None
    effectiveTopK: int | None = None
    personalizationApplied: bool | None = None
    latencyMs: int | None = None
    coverage: Coverage | Coverage1 | None = None


class V1IntelligenceEdgeCasePostResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class Spot4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    location: GeoPoint
    activity: str
    spotId: str | None = None


class V1ProjectionsPortfolioPostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    spots: list[Spot4] = Field(..., max_length=50, min_length=1)
    scenarios: list[Scenario] = Field(..., min_length=1)
    horizonDecades: list[str] | None = None
    baselineDecade: BaselineDecade | None = None


class V1ProjectionsPortfolioPostResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class Spot5(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    location: GeoPoint
    activity: str
    spotId: str | None = None
    subSpotSlug: str | None = None


class V1ProjectionsAdaptationReportPostRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    spots: list[Spot5] = Field(..., min_length=1)
    scenarios: list[Scenario] = Field(..., min_length=1)
    horizonDecades: list[str] | None = None


class V1ProjectionsAdaptationReportPostResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class Variable(Enum):
    wind_speed_kn = "wind_speed_kn"
    wind_dir_deg = "wind_dir_deg"
    wave_height_m = "wave_height_m"
    temp_c = "temp_c"
    sea_surface_temp_c = "sea_surface_temp_c"
    pressure_hpa = "pressure_hpa"
    precip_mm = "precip_mm"


class QualityFlag(Enum):
    verified = "verified"
    unflagged = "unflagged"
    flagged_low_quality = "flagged_low_quality"


class Observation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    observedAt: AwareDatetime
    variable: Variable
    value: float
    qualityFlag: QualityFlag | None = None


class V1ObservationsPostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    stationId: UUID
    observations: list[Observation] = Field(..., max_length=1000, min_length=1)


class V1ObservationsPostResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class V1ObservationsStationsGetResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class StationClass(Enum):
    verified = "verified"
    unflagged = "unflagged"
    flagged_low_quality = "flagged_low_quality"


class V1ObservationsStationsPostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., max_length=120, min_length=1)
    point: GeoPoint
    altitudeM: int | None = None
    variables: list[Variable] = Field(..., min_length=1)
    stationClass: StationClass | None = None
    updateCadenceMinutes: int | None = Field(None, ge=1, le=1440)
    notes: str | None = Field(None, max_length=2000)


class V1ObservationsStationsPostResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class V1ObservationsStationsStationIdPatchRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str | None = Field(None, max_length=120, min_length=1)
    point: GeoPoint | None = None
    altitudeM: int | None = None
    variables: list[Variable] | None = Field(None, min_length=1)
    stationClass: StationClass | None = None
    updateCadenceMinutes: int | None = Field(None, ge=1, le=1440)
    active: bool | None = None
    notes: str | None = Field(None, max_length=2000)


class V1ObservationsStationsStationIdPatchResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class V1ObservationsStationsStationIdRecentGetParametersQuery(BaseModel):
    limit: int | None = Field(100, ge=1, le=1000)


class QualityFlag1(Enum):
    verified = "verified"
    unflagged = "unflagged"
    flagged_low_quality = "flagged_low_quality"
    NoneType_None = None


class Observation1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID
    stationId: UUID
    observedAt: AwareDatetime
    variable: Variable
    value: float
    qualityFlag: QualityFlag1 | None = None
    ingestedAt: AwareDatetime


class V1ObservationsStationsStationIdRecentGetResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    observations: list[Observation1]


class AcceptTerms(Enum):
    """
    Must be true — records ToS / Privacy / DPA acceptance.
    """

    boolean_True = True


class V1PublicSignupPostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    displayName: str = Field(..., max_length=200, min_length=1)
    contactEmail: EmailStr
    acceptTerms: AcceptTerms = Field(
        ..., description="Must be true — records ToS / Privacy / DPA acceptance."
    )
    turnstileToken: str | None = None


class V1PublicSignupPostResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class V1PublicSustainabilityIndexGetParametersQuery(BaseModel):
    from_: AwareDatetime = Field(..., alias="from")
    to: AwareDatetime
    zoneKm: float | None = Field(None, gt=0.0, le=500.0)
    k: int | None = Field(10, ge=2, le=1000)


class FieldType(Enum):
    GoableSustainabilityIndex = "GoableSustainabilityIndex"


class Period(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    from_: AwareDatetime = Field(..., alias="from")
    to: AwareDatetime


class Weights(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    carbonNeutralShare: float
    electrificationShare: float


class Methodology(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    indexFormula: str
    weights: Weights
    suppression: str
    notes: str


class Overall(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    index: float = Field(..., ge=0.0, le=100.0)
    totalSessions: int = Field(..., ge=0)
    carbonNeutralSessions: int = Field(..., ge=0)
    carbonPositiveSessions: int = Field(..., ge=0)
    carbonNeutralShare: float = Field(..., ge=0.0, le=1.0)
    zonesReleased: int = Field(..., ge=0)
    zonesSuppressed: int = Field(..., ge=0)


class Zone(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    zoneKey: str
    label: str | None
    centroid: GeoPoint | None
    totalSessions: int = Field(..., ge=0)
    carbonNeutralShare: float = Field(..., ge=0.0, le=1.0)
    electrificationShare: float | None = Field(..., ge=0.0, le=1.0)
    seasonalConcentration: float | None = Field(..., ge=0.0, le=1.0)
    zoneIndex: float = Field(..., ge=0.0, le=100.0)


class License(Enum):
    CC_BY_4_0 = "CC BY 4.0"


class V1PublicSustainabilityIndexGetResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    field_context: str = Field(..., alias="@context", examples=["https://schema.org"])
    field_type: FieldType = Field(..., alias="@type")
    generatedAt: AwareDatetime
    period: Period
    methodology: Methodology
    overall: Overall
    zones: list[Zone]
    license: License
    attribution: str


class V1ResearchVerificationExportGetParametersQuery(BaseModel):
    from_: AwareDatetime | None = Field(None, alias="from")
    to: AwareDatetime | None = None


class Totals(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    activities: int
    subSpots: int
    clusters: int
    regions: int
    countries: int


class Family(Enum):
    water = "water"
    snow = "snow"
    air = "air"
    land = "land"


class Cluster(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    slug: str | None = None
    displayName: str | None = None
    countryCode: str | None = None
    subSpotCount: int | None = None


class Status4(Enum):
    """
    seeded ≥10 sub-spots · partial 1-9 · empty 0
    """

    seeded = "seeded"
    partial = "partial"
    empty = "empty"


class ByActivityItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    slug: str | None = None
    family: Family | None = None
    displayName: str | None = None
    subSpotCount: int | None = None
    clusterCount: int | None = None
    countryCount: int | None = None
    countries: list[str] | None = None
    clusters: list[Cluster] | None = None
    status: Status4 | None = Field(None, description="seeded ≥10 sub-spots · partial 1-9 · empty 0")
    lastUpdatedAt: AwareDatetime | None = Field(
        None,
        description="Newest commit touching the activity dir (null when no sub-spots yet)",
    )


class V1PublicCatalogStatsGetResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    computedAt: AwareDatetime = Field(..., description="ISO timestamp the bundled JSON was computed at")
    catalogVersion: str = Field(..., description="Catalog package version (mirrors package.json)")
    totals: Totals
    byActivity: list[ByActivityItem] = Field(
        ..., description="One entry per base profile, sorted DESC by subSpotCount."
    )


class EquipmentType(Enum):
    """
    Stream G equipment-transition signal.
    """

    electric = "electric"
    combustion = "combustion"
    manual = "manual"


class V1OutcomesPostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    occurred_at: AwareDatetime
    activity_slug: str = Field(..., min_length=1)
    outcome_type: OutcomeType
    spot_id: str | None = Field(None, description="Optional catalogue sub-spot slug.")
    audit_log_id: str | None = Field(None, description="Optional link back to a scoring_audit_log row.")
    detail: dict[str, Any] | None = None
    equipment_type: EquipmentType | None = Field(None, description="Stream G equipment-transition signal.")


class V1OutcomesPostResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class Format(Enum):
    csv = "csv"
    json = "json"


class V1AuditExportGetParametersQuery(BaseModel):
    from_: AwareDatetime = Field(..., alias="from")
    to: AwareDatetime
    format: Format | None = "json"
    limit: int | None = Field(None, ge=1, le=5000)
    offset: int | None = Field(None, ge=0)


class Window(BaseModel):
    from_: str | None = Field(None, alias="from")
    to: str | None = None


class Meta(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    total: int
    limit: int
    offset: int
    window: Window


class V1AuditExportGetResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    rows: list[dict[str, Any]]
    meta: Meta


class Document(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID
    kind: str
    version: str
    title: str
    body: str
    contentHash: str
    status: str
    createdAt: AwareDatetime
    publishedAt: AwareDatetime | None


class V1LegalKindCurrentGetResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    document: Document


class ScoreResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    score: float = Field(..., ge=0.0, le=100.0)
    verdict: Verdict
    confidence: float = Field(..., ge=0.0, le=1.0)
    breakdown: list[BreakdownItem]
    physics: dict[str, Any]
    alerts: list[Alert]
    eco: dict[str, Any]
    distribution: dict[str, Any] | None = Field(None, description="Present on ensemble requests")
    confidenceDetail: ConfidenceDetailForecast | None = None
    calibration_provenance: CalibrationProvenance | None = None
    assimilation: dict[str, Any] | None = None


class ConfidenceDetail(
    RootModel[ConfidenceDetailForecast | ConfidenceDetailHistorical | ConfidenceDetailClimate]
):
    root: ConfidenceDetailForecast | ConfidenceDetailHistorical | ConfidenceDetailClimate = Field(
        ..., discriminator="mode"
    )


class V1IntelligenceExplainPostRequest(BaseModel):
    """
    Provide exactly one of scoreResult or session_id.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    location: GeoPoint
    scoreResult: ScoreResponse | None = None
    session_id: UUID | None = None
    locale: Locale | None = None
    model: Model1 | None = None


class V1IntelligenceEdgeCasePostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    location: GeoPoint
    scoreResult: ScoreResponse | None = None
    session_id: UUID | None = None
    locale: Locale | None = None
    model: Model1 | None = None
