# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-08-13T07:24:33+00:00

from __future__ import annotations

from enum import Enum, IntEnum
from typing import Any, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, EmailStr, Field, RootModel


class GeoPoint(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    lat: float = Field(..., examples=[36.0133])
    lng: float = Field(..., examples=[-5.6044])


class TimeWindow(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    from_: AwareDatetime = Field(..., alias="from")
    to: AwareDatetime


class Error1(Enum):
    """
    Machine-readable error code — the stable field to switch on (the human `message` is not stable and not localized). The enum is the canonical registry from the API's `httpErrors.ts`; a client should still keep a generic fallback for a code added by a future release.

    The three 402 'upgrade needed' codes are distinct and NOT interchangeable:
    - `PAYMENT_REQUIRED` — a specific premium capability was requested on a plan that doesn't include it (e.g. ensemble scoring, or historical/portfolio scoring, on Free/Starter). Emitted inline by /v1/score, /v1/score/series, /v1/score/multi, /v1/score/historical, /v1/score/portfolio, /v1/underwriting/*, /v1/projections.
    - `PLAN_UPGRADE_REQUIRED` — a whole endpoint is gated below a minimum plan tier (the `requirePlanAtLeast` middleware). Emitted by e.g. /v1/score/difficulty and other Pro+/Scale-gated routes.
    - `PLAN_LIMIT_EXCEEDED` — the plan is allowed but a per-plan numeric cap was exceeded (e.g. recommend radiusKm / topK). Emitted by /v1/recommend-spot; carries `detail.maxKm` / `detail.maxTopK`.
    """

    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    CONFLICT = "CONFLICT"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    RATE_LIMITED = "RATE_LIMITED"
    PLAN_UPGRADE_REQUIRED = "PLAN_UPGRADE_REQUIRED"
    PLAN_LIMIT_EXCEEDED = "PLAN_LIMIT_EXCEEDED"
    PAYMENT_REQUIRED = "PAYMENT_REQUIRED"
    SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
    AUDIT_LOG_NOT_FOUND = "AUDIT_LOG_NOT_FOUND"
    ACTIVITY_NOT_FOUND = "ACTIVITY_NOT_FOUND"
    API_KEY_NOT_FOUND = "API_KEY_NOT_FOUND"
    TENANT_NOT_FOUND = "TENANT_NOT_FOUND"
    PAID_PLAN_REQUIRES_STRIPE_CUSTOMER = "PAID_PLAN_REQUIRES_STRIPE_CUSTOMER"
    CUSTOM_TENANT_STRIPE_CONFLICT = "CUSTOM_TENANT_STRIPE_CONFLICT"
    STRIPE_CUSTOMER_TAKEN = "STRIPE_CUSTOMER_TAKEN"
    UNKNOWN_SCOPES = "UNKNOWN_SCOPES"
    SESSION_LOOKUP_UNAVAILABLE = "SESSION_LOOKUP_UNAVAILABLE"
    MAX_BRIEFING_SLOTS_EXCEEDED = "MAX_BRIEFING_SLOTS_EXCEEDED"
    OUT_OF_EDGE_CASE_RANGE = "OUT_OF_EDGE_CASE_RANGE"
    LLM_BUDGET_EXCEEDED = "LLM_BUDGET_EXCEEDED"
    LLM_KEY_INVALID = "LLM_KEY_INVALID"
    WINDOW_TOO_LARGE = "WINDOW_TOO_LARGE"
    FORECAST_HORIZON_EXCEEDED = "FORECAST_HORIZON_EXCEEDED"
    PORTFOLIO_TOO_LARGE = "PORTFOLIO_TOO_LARGE"
    MAX_ACTIVITIES_EXCEEDED = "MAX_ACTIVITIES_EXCEEDED"
    ARCHIVE_UNAVAILABLE = "ARCHIVE_UNAVAILABLE"
    INVALID_YEARS_RANGE = "INVALID_YEARS_RANGE"
    MARINE_NOT_AVAILABLE = "MARINE_NOT_AVAILABLE"
    INVALID_TRIGGER = "INVALID_TRIGGER"
    QUOTE_NOT_FOUND = "QUOTE_NOT_FOUND"
    QUOTE_EXPIRED = "QUOTE_EXPIRED"
    QUOTE_ALREADY_BOUND = "QUOTE_ALREADY_BOUND"
    POLICY_NOT_FOUND = "POLICY_NOT_FOUND"
    POLICY_STATE_TRANSITION = "POLICY_STATE_TRANSITION"
    POLICY_STATE = "POLICY_STATE"
    QUOTE_NOT_ISSUABLE = "QUOTE_NOT_ISSUABLE"
    CATALOG_DRIFT = "CATALOG_DRIFT"
    DRIFT_ACTIVE = "DRIFT_ACTIVE"
    HISTORICAL_UNAVAILABLE = "HISTORICAL_UNAVAILABLE"
    CLIMATE_UNAVAILABLE = "CLIMATE_UNAVAILABLE"
    PROJECTION_UNAVAILABLE = "PROJECTION_UNAVAILABLE"
    WEBHOOK_INVALID_SIGNATURE = "WEBHOOK_INVALID_SIGNATURE"
    SPOT_NOT_PRECOMPUTED = "SPOT_NOT_PRECOMPUTED"
    PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE"
    IDEMPOTENCY_KEY_CONFLICT = "IDEMPOTENCY_KEY_CONFLICT"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    INTELLIGENCE_UNAVAILABLE = "INTELLIGENCE_UNAVAILABLE"
    ADMIN_BOOTSTRAP_DISABLED = "ADMIN_BOOTSTRAP_DISABLED"
    PERSISTENCE_UNAVAILABLE = "PERSISTENCE_UNAVAILABLE"


class Error(BaseModel):
    error: Error1 = Field(
        ...,
        description="Machine-readable error code — the stable field to switch on (the human `message` is not stable and not localized). The enum is the canonical registry from the API's `httpErrors.ts`; a client should still keep a generic fallback for a code added by a future release.\n\nThe three 402 'upgrade needed' codes are distinct and NOT interchangeable:\n- `PAYMENT_REQUIRED` — a specific premium capability was requested on a plan that doesn't include it (e.g. ensemble scoring, or historical/portfolio scoring, on Free/Starter). Emitted inline by /v1/score, /v1/score/series, /v1/score/multi, /v1/score/historical, /v1/score/portfolio, /v1/underwriting/*, /v1/projections.\n- `PLAN_UPGRADE_REQUIRED` — a whole endpoint is gated below a minimum plan tier (the `requirePlanAtLeast` middleware). Emitted by e.g. /v1/score/difficulty and other Pro+/Scale-gated routes.\n- `PLAN_LIMIT_EXCEEDED` — the plan is allowed but a per-plan numeric cap was exceeded (e.g. recommend radiusKm / topK). Emitted by /v1/recommend-spot; carries `detail.maxKm` / `detail.maxTopK`.",
    )
    message: str | None = None
    issues: list[dict[str, Any]] | None = None
    detail: dict[str, Any] | None = None


class Verdict(Enum):
    unsafe = "unsafe"
    not_feasible = "not_feasible"
    poor = "poor"
    marginal = "marginal"
    fair = "fair"
    favorable = "favorable"
    excellent = "excellent"


class ScoreBasis(Enum):
    """
    Explicit discriminator for why `score`/`verdict` came out the way they did. 'forecast' = the normal path, every profile gate passed. 'gated' = a hard gate (safety or feasibility) tripped — `score` is forced to 0, but `breakdown`/`physics` still carry the real per-dimension conditions (each breakdown entry's `contribution` is zeroed, since nothing contributed to the gated 0, while `suitability`/`hasData` and the physics values stay populated) so a no-go response shows WHY. 'no_data' = no weather samples were available at all, so `breakdown`/`physics` are genuinely empty. Do not infer gate/no-data from `breakdown` emptiness — a gate trip populates `breakdown` too; read this field instead.
    """

    forecast = "forecast"
    gated = "gated"
    no_data = "no_data"


class BreakdownItem(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    name: str | None = None
    value: float | None = Field(
        None,
        description="The raw physical reading for this dimension, in its native unit — this is the operational number to show an operator. Units are per-dimension: wind is KNOTS (e.g. `wind_speed`), wave height METRES (`wave` / `wave_height`), wave period SECONDS (`wave_period`), temperature °C (`air_temp_comfort`, `water_temp`), visibility KM (`visibility`), direction DEGREES. (The engine's full derived `summary` block is intentionally not returned; read operational numbers from here.)",
    )
    suitability: float | None = Field(
        None,
        description="0-1 desirability of `value` for this activity (the profile curve's output) — good for a per-dimension green/amber/red indicator. Distinct from `value`: `value` is the measurement, `suitability` is how good that measurement is.",
    )
    weight: float | None = None
    contribution: float | None = Field(
        None,
        description='This dimension\'s weighted contribution to `score`. Zeroed on a `scoreBasis: "gated"` response — nothing contributed to a gated 0 (Σcontribution = 0 = score) — even though `suitability`/`hasData` above still reflect the real conditions.',
    )
    hasData: bool | None = None
    prerequisite: bool | None = Field(
        None,
        description="True when this dimension's metric carries a feasibility gate — a HARD prerequisite. Below/above its threshold the activity is impossible and the whole score is gated to 0, rather than this dimension merely being weighted. Lets a go/no-go client tell hard prerequisites from soft weighted dimensions straight from the breakdown. Present from catalog v2.4.0 (false on older catalogs).",
    )


class Level(Enum):
    info = "info"
    warning = "warning"
    critical = "critical"


class Kind(Enum):
    """
    On a gate-trip alert, why the activity is a no-go: 'safety' = dangerous conditions; 'feasibility' = impossible at any skill level (e.g. no rideable wind). Absent on non-gate alerts. Present from catalog v2.4.0.
    """

    safety = "safety"
    feasibility = "feasibility"


class Alert(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    level: Level | None = None
    code: str | None = Field(
        None,
        description="Stable, machine-readable alert identifier — the field to key a UI, an icon map, or a localized message off (NOT `description`, which is English debug prose and is not localized). Deliberately an open string, not a closed enum: engine codes are fixed in source (NO_DATA, MISSING_DIMENSION_DATA, SAFETY_GATE_UNEVALUATED, SCORE_FLOORED, SAFETY_DATA_UNAVAILABLE, FEASIBILITY_GATE_OBSERVATION_OVERRIDE, and the observed-safety codes ACTIVE_THUNDERSTORM_RISK / ELEVATED_LIGHTNING_RISK / AQI_HAZARDOUS / AQI_VERY_UNHEALTHY / AQI_UNHEALTHY_FOR_ENDURANCE), while gate-trip codes come from the activity profile's catalog and are stable within a profiles-catalog major version (e.g. water sports: NO_RIDABLE_WIND, GALE_FORCE_WIND, HEAVY_RAIN, LOW_VISIBILITY, FLAT_NO_SURF, EXTREME_SURF, HIGH_WIND, STRONG_WIND, RIP_CURRENT_HAZARD, HIGH_SEAS, POOR_SURFACE_VISIBILITY, POOR_UNDERWATER_VISIBILITY, STRONG_CURRENT_UNSAFE). Map known codes; keep a generic fallback for codes added by a future catalog version.",
    )
    description: str | None = Field(
        None,
        description="Human-readable English explanation of the alert. Debug / fallback copy only — it is NOT localized. Localize your UI off `code`, not this field.",
    )
    kind: Kind | None = Field(
        None,
        description="On a gate-trip alert, why the activity is a no-go: 'safety' = dangerous conditions; 'feasibility' = impossible at any skill level (e.g. no rideable wind). Absent on non-gate alerts. Present from catalog v2.4.0.",
    )


class Granularity(Enum):
    """
    Bucket granularity used for the series (defaults to `hourly` when the request omits it). Always returned.
    """

    hourly = "hourly"
    field_3_hourly = "3-hourly"
    daily = "daily"


class Kind1(Enum):
    safety = "safety"
    feasibility = "feasibility"


class Alert1(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    level: Level | None = None
    code: str | None = None
    description: str | None = None
    kind: Kind1 | None = None


class Series(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    timestamp: AwareDatetime
    score: float
    verdict: Verdict
    confidence: float
    alerts: list[Alert1] = Field(
        ...,
        description="Per-bucket scoring alerts (same shape as /v1/score and /v1/score-multi). A bucket forced to unsafe/0 carries its gate reason here — alerts[].kind = 'safety' | 'feasibility'.",
    )


class ScoreSeriesResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    session_id: UUID = Field(
        ...,
        description="Correlation id for this time-series call. Always returned. NOTE: like /v1/score/multi and unlike POST /v1/score, this is NOT linkable — /v1/score/series does not write a `scoring_audit_log` row, so passing it as `audit_log_id` on POST /v1/outcomes is rejected 404. Only single POST /v1/score session_ids close the calibration loop.",
    )
    profile_slug: str = Field(
        ...,
        description="Resolved catalog profile slug for the requested activity. Always returned.",
    )
    granularity: Granularity = Field(
        ...,
        description="Bucket granularity used for the series (defaults to `hourly` when the request omits it). Always returned.",
    )
    series: list[Series]


class BreakdownItem1(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    name: str | None = None
    value: float | None = None
    suitability: float | None = None
    weight: float | None = None
    contribution: float | None = None
    hasData: bool | None = None
    prerequisite: bool | None = Field(
        None,
        description="True when this dimension's metric carries a feasibility gate (a HARD prerequisite) — see /v1/score breakdown[].prerequisite. Present from catalog v2.4.0.",
    )


class Alert2(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    level: Level | None = None
    code: str | None = None
    description: str | None = None
    kind: Kind1 | None = None


class Result(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    activity: str
    profile_slug: str | None = None
    score: float | None = Field(None, ge=0.0, le=100.0)
    verdict: Verdict | None = None
    confidence: float | None = Field(None, ge=0.0, le=1.0)
    breakdown: list[BreakdownItem1] | None = None
    distribution: dict[str, Any] | None = Field(None, description="Present on ensemble requests")
    alerts: list[Alert2] | None = Field(
        None,
        description="Per-activity scoring alerts (same shape as /v1/score). verdict = 'not_feasible' already distinguishes an impossible-but-not-dangerous read (e.g. no rideable wind) from 'unsafe'; alerts[].kind = 'feasibility' on the triggering alert carries the same signal for callers that want the underlying reason.",
    )
    error: str | None = Field(
        None,
        description='"ACTIVITY_NOT_FOUND" when the activity slug does not resolve.',
    )


class ScoreMultiResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    session_id: UUID = Field(
        ...,
        description="Correlation id for this multi-activity call. Always returned. NOTE: unlike a POST /v1/score `session_id`, this is NOT linkable — /v1/score/multi does not write a `scoring_audit_log` row, so passing it as `audit_log_id` on POST /v1/outcomes is rejected 404. Only single POST /v1/score session_ids close the calibration loop.",
    )
    location: GeoPoint | None = None
    results: list[Result]
    rankedByScore: list[str] | None = Field(
        None,
        description="Activity slugs sorted by score descending; errored activities are omitted.",
    )


class Level3(Enum):
    sub_spot = "sub-spot"
    cluster = "cluster"
    region = "region"
    base = "base"


class Tier(IntEnum):
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3


class TierSource(Enum):
    catalog = "catalog"
    classifier = "classifier"


class CalibrationProvenance(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    level: Level3 | None = None
    slug: str | None = None
    scoring_profile_slug: str | None = None
    sub_spot_slug: str | None = None
    distance_to_sub_spot_m: float | None = None
    tier: Tier | None = None
    tier_source: TierSource | None = None


class Level4(Enum):
    base = "base"
    region = "region"
    cluster = "cluster"
    sub_spot = "sub-spot"


class CalibrationProvenanceSummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    level: Level4
    n_local: int | None
    shrinkage_weight_from_parent: float | None = Field(..., ge=0.0, le=1.0)


class Severity(Enum):
    watch = "watch"
    warning = "warning"
    critical = "critical"


class Cell(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    activity: str
    sub_spot: str
    horizon_h: int


class Metric(Enum):
    decision_bss = "decision_bss"


class ReferenceType(Enum):
    operator_outcome = "operator_outcome"


class DriftFlag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    severity: Severity
    since_timestamp: AwareDatetime
    cell: Cell
    metric: Metric
    reference_type: ReferenceType
    days_in_decline: int
    recalibration_triggered: bool


class Mode(Enum):
    forecast = "forecast"


class SkillCalibration(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    applied: bool
    n_train: int
    cohort_hash: str
    scalar: float = Field(..., ge=0.85, le=1.0)


class ConfidenceDetailForecast(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    mode: Literal["forecast"]
    forecast_skill: float = Field(
        ...,
        description="[0,1] skill factor in the confidence fold. It now DECAYS with forecast lead time (nowcast ≈ 0.90, ~0.78 at 24h, ~0.69 at 72h, ~0.60 at 7 days, ~0.51 at the ~16-day limit) rather than being flat, so a near-term bucket scores higher than a far-out one. This is a cold-start prior keyed on lead time, not yet a measurement of per-stratum skill; it is replaced factor-for-factor when measured skill is available.",
        ge=0.0,
        le=1.0,
    )
    provider_agreement: float = Field(
        ...,
        description="[0,1] agreement across consensus constituents. Defaults to 1.0 for the single-provider (or unmeasured) case — no penalty for the absence of a second opinion; < 1.0 only when ≥2 constituents returned samples and diverged.",
        ge=0.0,
        le=1.0,
    )
    profile_maturity: float = Field(
        ...,
        description="[0,1] catalog-maturity factor: provisional 0.75 → reviewed 0.85 → calibrated 0.95. RISES as the activity profile is outcome-calibrated.",
        ge=0.0,
        le=1.0,
    )
    hierarchical_calibration: float = Field(..., ge=0.0, le=1.0)
    calibration_provenance: CalibrationProvenanceSummary | None = None
    skill_calibration: SkillCalibration | None = None
    drift_flag: DriftFlag | None = None


class Mode1(Enum):
    historical = "historical"


class ConfidenceDetailHistorical(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    mode: Literal["historical"]
    sample_size_confidence: float = Field(..., ge=0.0, le=1.0)
    base_climatology_quality: float = Field(..., ge=0.0, le=1.0)
    calibration_confidence: float = Field(..., ge=0.0, le=1.0)
    hierarchical_calibration: float = Field(..., ge=0.0, le=1.0)
    calibration_provenance: CalibrationProvenanceSummary | None = None
    drift_flag: DriftFlag | None = None


class Mode2(Enum):
    climate = "climate"


class ConfidenceDetailClimate(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    mode: Literal["climate"]
    model_spread: float = Field(..., ge=0.0, le=1.0)
    bias_correction_residual: float = Field(..., ge=0.0, le=1.0)
    scenario_uncertainty: float = Field(..., ge=0.0, le=1.0)
    horizon_uncertainty: float = Field(..., ge=0.0, le=1.0)
    hierarchical_calibration: float = Field(..., ge=0.0, le=1.0)
    calibration_provenance: CalibrationProvenanceSummary | None = None
    drift_flag: DriftFlag | None = None


class Status(Enum):
    bound = "bound"
    triggered = "triggered"
    settled = "settled"
    expired = "expired"


class PayoutCurrency(Enum):
    EUR = "EUR"
    USD = "USD"
    GBP = "GBP"
    CHF = "CHF"


class PremiumCollection(Enum):
    external = "external"
    stripe = "stripe"
    invoice_due = "invoice_due"


class CoverageWindow(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    monthFrom: int = Field(..., ge=1, le=12)
    dayFrom: int = Field(..., ge=1, le=31)
    monthTo: int = Field(..., ge=1, le=12)
    dayTo: int = Field(..., ge=1, le=31)


class SerialisedPolicy(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID
    tenantId: UUID
    quoteId: UUID
    status: Status
    payoutAmount: float | None = Field(
        None,
        description="Null for mixed-currency portfolios; the breakdown lives on the underlying quote.",
    )
    payoutCurrency: PayoutCurrency | None = None
    premiumPaid: float | None = None
    premiumCollection: PremiumCollection
    coverageWindow: CoverageWindow
    coverageYear: int = Field(..., ge=2000, le=2100)
    trigger: dict[str, Any] = Field(
        ...,
        description="Frozen at bind time — same shape as the quote's normalised trigger.",
    )
    policyTerms: dict[str, Any] = Field(
        ...,
        description="Frozen snapshot of the per-spot profile + payout terms — decouples the policy from later catalog changes.",
    )
    boundAt: AwareDatetime
    triggeredAt: AwareDatetime | None
    settledAt: AwareDatetime | None
    expiredAt: AwareDatetime | None
    settlementReference: str | None


class EvaluationSource(Enum):
    manual = "manual"
    scheduled = "scheduled"


class SerialisedPayoutEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID
    policyId: UUID
    spotIndex: int = Field(..., ge=0)
    eventStartAt: AwareDatetime
    eventEndAt: AwareDatetime
    hoursFired: float
    payoutAmount: float
    payoutCurrency: PayoutCurrency
    detectedAt: AwareDatetime
    evaluationSource: EvaluationSource


class HistoricalYearsRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    from_: int = Field(..., alias="from")
    to: int


class Currency(Enum):
    EUR = "EUR"
    USD = "USD"
    GBP = "GBP"
    CHF = "CHF"


class Payout(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    amount: float = Field(..., gt=0.0)
    currency: Currency


class Tier1(Enum):
    """
    Sub-spot tier (1/2/3) applied to the tier risk multiplier; null when no sub-spot resolved.
    """

    int_1 = 1
    int_2 = 2
    int_3 = 3
    NoneType_None = None


class TierSource1(Enum):
    """
    Provenance of the tier: 'catalog' from profile YAML, 'classifier' from L11 confidence=1.0 override, null when no tier applied.
    """

    catalog = "catalog"
    classifier = "classifier"
    NoneType_None = None


class Spot(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resolvedProfileSlug: str
    point: GeoPoint
    spotId: str | None = None
    payout: Payout
    tier: Tier1 | None = Field(
        None,
        description="Sub-spot tier (1/2/3) applied to the tier risk multiplier; null when no sub-spot resolved.",
    )
    tierSource: TierSource1 | None = Field(
        None,
        description="Provenance of the tier: 'catalog' from profile YAML, 'classifier' from L11 confidence=1.0 override, null when no tier applied.",
    )


class Payout1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    amount: float = Field(..., gt=0.0)
    currency: Currency


class PortfolioItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resolvedProfileSlug: str
    point: GeoPoint
    spotId: str | None = None
    payout: Payout1
    tier: Tier1 | None = Field(
        None,
        description="Sub-spot tier (1/2/3) applied to the tier risk multiplier; null when no sub-spot resolved.",
    )
    tierSource: TierSource1 | None = Field(
        None,
        description="Provenance of the tier: 'catalog' from profile YAML, 'classifier' from L11 confidence=1.0 override, null when no tier applied.",
    )


class Policy(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    coverageWindow: CoverageWindow
    trigger: dict[str, Any] = Field(
        ...,
        description="Normalised trigger echoed back with defaulted consecutiveHours/cooldownHours.",
    )
    historicalYearsRange: HistoricalYearsRange
    spot: Spot | None = None
    portfolio: list[PortfolioItem] | None = None


class EUR(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    mean: float
    p10: float
    p50: float
    p90: float
    perYear: list[float]
    varianceStability: float = Field(..., ge=0.0, le=1.0)


class USD(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    mean: float
    p10: float
    p50: float
    p90: float
    perYear: list[float]
    varianceStability: float = Field(..., ge=0.0, le=1.0)


class GBP(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    mean: float
    p10: float
    p50: float
    p90: float
    perYear: list[float]
    varianceStability: float = Field(..., ge=0.0, le=1.0)


class CHF(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    mean: float
    p10: float
    p50: float
    p90: float
    perYear: list[float]
    varianceStability: float = Field(..., ge=0.0, le=1.0)


class ByCurrency(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    EUR_1: EUR | None = Field(None, alias="EUR")
    USD_1: USD | None = Field(None, alias="USD")
    GBP_1: GBP | None = Field(None, alias="GBP")
    CHF_1: CHF | None = Field(None, alias="CHF")


class ExpectedPayouts(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    byCurrency: ByCurrency


class EUR1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    fair: float
    loaded: float
    tierMultiplierWeightedAvg: float = Field(
        ...,
        description="Weighted-average tier risk multiplier applied across spots in this currency (1.0 when no sub-spot).",
    )


class USD1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    fair: float
    loaded: float
    tierMultiplierWeightedAvg: float = Field(
        ...,
        description="Weighted-average tier risk multiplier applied across spots in this currency (1.0 when no sub-spot).",
    )


class GBP1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    fair: float
    loaded: float
    tierMultiplierWeightedAvg: float = Field(
        ...,
        description="Weighted-average tier risk multiplier applied across spots in this currency (1.0 when no sub-spot).",
    )


class CHF1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    fair: float
    loaded: float
    tierMultiplierWeightedAvg: float = Field(
        ...,
        description="Weighted-average tier risk multiplier applied across spots in this currency (1.0 when no sub-spot).",
    )


class ByCurrency1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    EUR: EUR1 | None = None
    USD: USD1 | None = None
    GBP: GBP1 | None = None
    CHF: CHF1 | None = None


class ExpectedPremium(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    byCurrency: ByCurrency1
    loadingFactor: float = Field(..., ge=0.0, le=2.0)


class AdvisoryLevel(Enum):
    high_confidence = "high_confidence"
    moderate_confidence = "moderate_confidence"
    low_confidence = "low_confidence"


class UnderwritingQuoteResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    policy: Policy
    expectedPayouts: ExpectedPayouts
    expectedPremium: ExpectedPremium
    modelConfidence: float = Field(..., ge=0.0, le=1.0)
    advisoryLevel: AdvisoryLevel
    issuable: bool
    notes: list[str]
    underlying: dict[str, Any] | list[dict[str, Any]] = Field(
        ...,
        description="HistoricalScoreDistribution — object for single spot, array for portfolio.",
    )
    quoteId: UUID | None = Field(
        None,
        description="Present when the policy store is wired — pass to /v1/underwriting/policy/bind to bind this quote.",
    )
    expiresAt: AwareDatetime | None = Field(
        None, description="ISO timestamp after which the quote can no longer be bound."
    )
    boundPolicyId: UUID | None = Field(
        None,
        description="Present on GET after the quote has been bound — the resulting policy id.",
    )


class WebhookEvent(Enum):
    outcome_created = "outcome.created"
    drift_fired = "drift.fired"
    drift_resolved = "drift.resolved"
    calibration_completed = "calibration.completed"
    billing_subscription_updated = "billing.subscription_updated"
    recommendation_completed = "recommendation.completed"
    underwriting_policy_bound = "underwriting.policy.bound"
    underwriting_policy_triggered = "underwriting.policy.triggered"
    underwriting_policy_settled = "underwriting.policy.settled"


class V1HealthGetResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class V1HealthReadyGetResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class RiderSkillLevel(Enum):
    """
    Skill-conditioned scoring (Pro+).
    """

    beginner = "beginner"
    intermediate = "intermediate"
    expert = "expert"


class V1ScorePostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    activity: str = Field(..., examples=["kitesurfing"])
    location: GeoPoint
    window: TimeWindow | None = None
    ensemble: bool | None = Field(None, description="L2a probabilistic ensemble (Pro+)")
    members: int | None = Field(None, ge=2, le=50)
    rider_skill_level: RiderSkillLevel | None = Field(None, description="Skill-conditioned scoring (Pro+).")


class Activity(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    slug: str = Field(..., examples=["kitesurfing"])
    display_name: str = Field(..., examples=["Kitesurfing"])
    family: str = Field(
        ...,
        description="Activity category (water/snow/air/land/commercial).",
        examples=["water"],
    )


class V1ActivitiesGetResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    activities: list[Activity]


class Activity1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    slug: str = Field(..., examples=["kitesurfing"])
    display_name: str = Field(..., examples=["Kitesurfing"])
    family: str = Field(..., examples=["water"])


class V1ProfilesGetResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    activities: list[Activity1]


class Granularity1(Enum):
    hourly = "hourly"
    field_3_hourly = "3-hourly"
    daily = "daily"


class V1ScoreSeriesPostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    activity: str
    location: GeoPoint
    window: TimeWindow
    granularity: Granularity1 | None = None
    ensemble: bool | None = None
    members: int | None = Field(None, ge=2, le=50)


class V1ScoreMultiPostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    activities: list[str] = Field(..., max_length=10, min_length=1)
    location: GeoPoint
    window: TimeWindow | None = None
    ensemble: bool | None = None
    members: int | None = Field(None, ge=2, le=50)


class YearsRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    from_: int = Field(..., alias="from", ge=1940)
    to: int


class Granularity2(Enum):
    month = "month"
    week = "week"
    day_of_year = "day-of-year"
    daypart = "daypart"


class Daypart(Enum):
    morning = "morning"
    midday = "midday"
    afternoon = "afternoon"
    evening = "evening"


class Selector(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    month: int | None = Field(None, ge=1, le=12)
    weekOfYear: int | None = Field(None, ge=1, le=53)
    dayOfYear: int | None = Field(None, ge=1, le=366)
    daypart: Daypart | None = None


class V1ScoreHistoricalPostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    activity: str
    location: GeoPoint
    yearsRange: YearsRange
    granularity: Granularity2
    selector: Selector
    failOnMarineGap: bool | None = None


class V1ScoreHistoricalPostResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class Spot1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    location: GeoPoint
    activity: str
    weight: float | None = Field(None, gt=0.0)
    spotId: str | None = None


class Selector1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    month: int | None = Field(None, ge=1, le=12)
    weekOfYear: int | None = Field(None, ge=1, le=53)
    dayOfYear: int | None = Field(None, ge=1, le=366)
    daypart: Daypart | None = None


class Model(Enum):
    none = "none"
    exponential = "exponential"


class Correlation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    model: Model | None = None
    lengthKm: float | None = Field(None, gt=0.0)


class V1ScorePortfolioPostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    spots: list[Spot1] = Field(..., max_length=50, min_length=1)
    yearsRange: YearsRange
    granularity: Granularity2
    selector: Selector1
    correlation: Correlation | None = None
    cancellationThreshold: float | None = Field(None, ge=0.0, le=100.0)


class V1ScorePortfolioPostResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class Include(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    marginal_sensitivities: bool | None = None
    binding_constraint: bool | None = None
    best_window_24h: bool | None = None
    best_nearby_spot_km: float | None = Field(None, le=200.0)
    natural_language: bool | None = Field(
        None,
        description="LLM explanation. Available on any plan (Anthropic BYOK) — resolves the tenant's own Anthropic key set via PUT /v1/tenant/llm-key; no key configured degrades to a deterministic template (natural_language.degraded_mode=true) rather than an error.",
    )


class V1ScoreExplainCounterfactualPostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    activity: str = Field(..., max_length=64)
    spot: GeoPoint
    window: TimeWindow
    include: Include | None = None


class V1ScoreExplainCounterfactualPostResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class Experience(Enum):
    beginner = "beginner"
    intermediate = "intermediate"
    advanced = "advanced"
    expert = "expert"


class RiskTolerance(Enum):
    conservative = "conservative"
    moderate = "moderate"
    aggressive = "aggressive"


class OwnedGearItem(RootModel[str]):
    root: str = Field(..., max_length=64)


class UserProfile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    experience: Experience | None = None
    weight_kg: float | None = Field(None, gt=0.0, le=300.0)
    risk_tolerance: RiskTolerance | None = None
    owned_gear: list[OwnedGearItem] | None = Field(None, max_length=20)


class V1DecisionPostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    user_pseudonym: str = Field(
        ...,
        description="SHA256(user_id + secret)[:32], hex ≥32 chars. NEVER PII.",
        min_length=32,
        pattern="^[0-9a-fA-F]+$",
    )
    activity: str = Field(..., max_length=64)
    spot: GeoPoint
    window: TimeWindow
    user_profile: UserProfile | None = None
    training_consent: bool | None = False


class V1DecisionPostResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class Locale(Enum):
    en = "en"
    it = "it"


class Model1(Enum):
    claude_haiku_4_5_20251001 = "claude-haiku-4-5-20251001"
    claude_sonnet_4_6 = "claude-sonnet-4-6"


class V1IntelligenceExplainPostResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class V1IntelligenceBriefingPostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    activity: str
    slots: list[dict[str, Any]]
    locale: Locale | None = None
    model: Model1 | None = None


class V1IntelligenceBriefingPostResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class V1TenantLlmKeyPutRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    apiKey: str = Field(
        ...,
        description="The tenant's own Anthropic API key (sk-ant-...).",
        max_length=300,
        min_length=20,
    )


class V1TenantLlmKeyGetResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    set: bool
    last4: str | None = None
    setAt: AwareDatetime | None = None
    lastValidatedAt: AwareDatetime | None = None


class Spot2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    location: GeoPoint
    activity: str
    spotId: str | None = None


class Scenario(Enum):
    SSP1_2_6 = "SSP1-2.6"
    SSP2_4_5 = "SSP2-4.5"
    SSP3_7_0 = "SSP3-7.0"
    SSP5_8_5 = "SSP5-8.5"


class BaselineDecade(Enum):
    field_2020s = "2020s"
    field_2030s = "2030s"


class V1ProjectionsPostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    spot: Spot2
    scenarios: list[Scenario] = Field(..., min_length=1)
    horizonDecades: list[str] | None = None
    baselineDecade: BaselineDecade | None = None


class V1ProjectionsPostResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class Payout2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    amount: float = Field(..., gt=0.0)
    currency: Currency


class Spot3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    point: GeoPoint
    activity: str = Field(..., min_length=1)
    spotId: str | None = None
    payout: Payout2


class Payout3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    amount: float = Field(..., gt=0.0)
    currency: Currency


class PortfolioItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    point: GeoPoint
    activity: str = Field(..., min_length=1)
    spotId: str | None = None
    payout: Payout3


class Kind3(Enum):
    scoreBelow = "scoreBelow"


class Trigger(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Kind3
    scoreBelow: float = Field(..., ge=0.0, le=100.0)
    consecutiveHours: int | None = Field(None, ge=1, le=72)
    cooldownHours: int | None = Field(None, ge=0, le=168)
    maxPayoutsPerYear: int | None = Field(None, ge=1)


class Kind4(Enum):
    verdictAtOrBelow = "verdictAtOrBelow"


class Trigger1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Kind4
    verdict: Verdict
    consecutiveHours: int | None = Field(None, ge=1, le=72)
    cooldownHours: int | None = Field(None, ge=0, le=168)
    maxPayoutsPerYear: int | None = Field(None, ge=1)


class HistoricalYearsRange1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    from_: int = Field(..., alias="from", ge=1940)
    to: int


class V1UnderwritingQuotePostRequest(BaseModel):
    """
    Provide exactly one of spot or portfolio.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    spot: Spot3 | None = None
    portfolio: list[PortfolioItem1] | None = Field(None, max_length=50, min_length=2)
    coverageWindow: CoverageWindow
    trigger: Trigger | Trigger1
    historicalYearsRange: HistoricalYearsRange1 | None = None
    loadingFactor: float | None = Field(None, ge=0.0, le=2.0)
    calibrationConfidenceMin: float | None = Field(None, ge=0.0, le=1.0)
    forceIssue: bool | None = None


class V1UnderwritingPolicyBindPostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    quoteId: UUID
    coverageYear: int = Field(..., ge=2000, le=2100)
    premiumCollection: PremiumCollection
    premiumPaid: float | None = Field(None, ge=0.0)


class Severity1(Enum):
    watch = "watch"


class DriftAdvisory(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    spotIndex: int = Field(..., ge=0)
    activity: str
    subSpotSlug: str
    severity: Severity1
    since: AwareDatetime


class V1UnderwritingPolicyBindPostResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    policy: SerialisedPolicy
    quoteId: UUID
    driftAdvisories: list[DriftAdvisory] | None = Field(
        None,
        description="Soft warnings for cells with an open watch-level L9 drift event. Present only when non-empty.",
    )


class V1UnderwritingPolicyGetParametersQuery(BaseModel):
    status: Status | None = None
    coverageYear: int | None = Field(None, ge=2000, le=2100)
    limit: int | None = Field(None, ge=1, le=200)
    cursor: UUID | None = None


class V1UnderwritingPolicyGetResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    policies: list[SerialisedPolicy]


class V1UnderwritingPolicyPolicyIdGetResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    policy: SerialisedPolicy
    events: list[SerialisedPayoutEvent]


class V1UnderwritingPolicyPolicyIdEvaluatePostResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    policy: SerialisedPolicy
    events: list[SerialisedPayoutEvent]
    inserted: int = Field(..., ge=0)
    skipped: int = Field(..., ge=0)


class V1UnderwritingPolicyPolicyIdSettlePostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    settlementReference: str = Field(..., max_length=256, min_length=1)
    settledAt: AwareDatetime | None = None


class V1UnderwritingPolicyPolicyIdSettlePostResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    policy: SerialisedPolicy


class OutcomeType(Enum):
    ran = "ran"
    cancelled = "cancelled"
    rescheduled = "rescheduled"
    no_show = "no_show"
    note = "note"


class ReasonCategory(Enum):
    """
    Structured cause when a session did not run as planned. Only 'weather' and 'safety' outcomes count as evidence against the forecast score and feed weather-suitability calibration; 'operational', 'customer_demand', 'mechanical', and 'unknown' are treated as business facts and excluded. Echoed on the outcome.created webhook.
    """

    weather = "weather"
    operational = "operational"
    customer_demand = "customer_demand"
    safety = "safety"
    mechanical = "mechanical"
    unknown = "unknown"


class V1ScoreSessionIdOutcomePostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    outcome_type: OutcomeType
    reason_category: ReasonCategory | None = Field(
        None,
        description="Structured cause when a session did not run as planned. Only 'weather' and 'safety' outcomes count as evidence against the forecast score and feed weather-suitability calibration; 'operational', 'customer_demand', 'mechanical', and 'unknown' are treated as business facts and excluded. Echoed on the outcome.created webhook.",
    )
    detail: dict[str, Any] | None = None


class V1ScoreSessionIdOutcomePostResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class V1ScoreDifficultyPostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    activity: str = Field(..., min_length=1)
    location: GeoPoint


class Level5(Enum):
    sub_spot = "sub-spot"
    cluster = "cluster"
    region = "region"
    base = "base"


class Resolved(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    level: Level5
    slug: str
    sub_spot_slug: str | None = None
    distance_to_sub_spot_m: float | None = None


class Dimension(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    dimension: str
    grid: list[float]
    difficulty: list[float]
    discrimination_a: float
    cohort_hash: str
    computed_at: AwareDatetime


class V1ScoreDifficultyPostResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resolved: Resolved
    dimensions: list[Dimension]


class V1RecommendSpotPostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    activity: str = Field(..., min_length=1)
    regionCenter: GeoPoint
    radiusKm: float = Field(..., gt=0.0)
    topK: int = Field(..., ge=1)
    window: TimeWindow | None = None
    userPseudonym: str | None = Field(
        None,
        description="Optional booking-platform-side pseudonym. When present, Pro+ tenants get personalization via the L6 cold-start blend (cap 0.5 weight).",
        max_length=128,
        min_length=1,
    )


class Result1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    spotSlug: str | None = None
    name: str | None = None
    location: GeoPoint | None = None
    distanceKm: float | None = None
    score: float | None = None
    effectiveScore: float | None = None
    verdict: str | None = None
    personalScore: float | None = None
    personalWeight: float | None = None
    rank: int | None = None


class Status2(Enum):
    no_subspots_in_radius = "no_subspots_in_radius"


class NearestSubSpot(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    slug: str
    name: str
    distanceKm: float


class SuggestedAction(Enum):
    expand_radius = "expand_radius"


class Coverage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: Status2
    nearestSubSpot: NearestSubSpot
    suggestedAction: SuggestedAction
    suggestedRadiusKm: float


class Status3(Enum):
    no_subspots_for_activity = "no_subspots_for_activity"


class SuggestedAction1(Enum):
    request_coverage = "request_coverage"


class Coverage1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: Status3
    suggestedAction: SuggestedAction1


class V1RecommendSpotPostResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    results: list[Result1] | None = None
    allGated: bool | None = None
    totalCandidates: int | None = None
    rankedCandidates: int | None = None
    effectiveRadiusKm: float | None = None
    effectiveTopK: int | None = None
    personalizationApplied: bool | None = None
    latencyMs: int | None = None
    coverage: Coverage | Coverage1 | None = None


class V1IntelligenceEdgeCasePostResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class Spot4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    location: GeoPoint
    activity: str
    spotId: str | None = None


class V1ProjectionsPortfolioPostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    spots: list[Spot4] = Field(..., max_length=50, min_length=1)
    scenarios: list[Scenario] = Field(..., min_length=1)
    horizonDecades: list[str] | None = None
    baselineDecade: BaselineDecade | None = None


class V1ProjectionsPortfolioPostResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class Spot5(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    location: GeoPoint
    activity: str
    spotId: str | None = None
    subSpotSlug: str | None = None


class V1ProjectionsAdaptationReportPostRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    spots: list[Spot5] = Field(..., min_length=1)
    scenarios: list[Scenario] = Field(..., min_length=1)
    horizonDecades: list[str] | None = None


class V1ProjectionsAdaptationReportPostResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class Variable(Enum):
    wind_speed_kn = "wind_speed_kn"
    wind_dir_deg = "wind_dir_deg"
    wave_height_m = "wave_height_m"
    temp_c = "temp_c"
    sea_surface_temp_c = "sea_surface_temp_c"
    pressure_hpa = "pressure_hpa"
    precip_mm = "precip_mm"


class QualityFlag(Enum):
    verified = "verified"
    unflagged = "unflagged"
    flagged_low_quality = "flagged_low_quality"


class Observation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    observedAt: AwareDatetime
    variable: Variable
    value: float
    qualityFlag: QualityFlag | None = None


class V1ObservationsPostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    stationId: UUID
    observations: list[Observation] = Field(..., max_length=1000, min_length=1)


class V1ObservationsPostResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class V1ObservationsStationsGetResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class StationClass(Enum):
    verified = "verified"
    unflagged = "unflagged"
    flagged_low_quality = "flagged_low_quality"


class V1ObservationsStationsPostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., max_length=120, min_length=1)
    point: GeoPoint
    altitudeM: int | None = None
    variables: list[Variable] = Field(..., min_length=1)
    stationClass: StationClass | None = None
    updateCadenceMinutes: int | None = Field(None, ge=1, le=1440)
    notes: str | None = Field(None, max_length=2000)


class V1ObservationsStationsPostResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class V1ObservationsStationsStationIdPatchRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str | None = Field(None, max_length=120, min_length=1)
    point: GeoPoint | None = None
    altitudeM: int | None = None
    variables: list[Variable] | None = Field(None, min_length=1)
    stationClass: StationClass | None = None
    updateCadenceMinutes: int | None = Field(None, ge=1, le=1440)
    active: bool | None = None
    notes: str | None = Field(None, max_length=2000)


class V1ObservationsStationsStationIdPatchResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class V1ObservationsStationsStationIdRecentGetParametersQuery(BaseModel):
    limit: int | None = Field(100, ge=1, le=1000)


class QualityFlag1(Enum):
    verified = "verified"
    unflagged = "unflagged"
    flagged_low_quality = "flagged_low_quality"
    NoneType_None = None


class Observation1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID
    stationId: UUID
    observedAt: AwareDatetime
    variable: Variable
    value: float
    qualityFlag: QualityFlag1 | None = None
    ingestedAt: AwareDatetime


class V1ObservationsStationsStationIdRecentGetResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    observations: list[Observation1]


class AcceptTerms(Enum):
    """
    Must be true — records ToS / Privacy / DPA acceptance.
    """

    boolean_True = True


class V1PublicSignupPostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    displayName: str = Field(..., max_length=200, min_length=1)
    contactEmail: EmailStr
    acceptTerms: AcceptTerms = Field(
        ..., description="Must be true — records ToS / Privacy / DPA acceptance."
    )
    turnstileToken: str | None = None


class V1PublicSignupPostResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class V1PublicSustainabilityIndexGetParametersQuery(BaseModel):
    year: int | None = Field(None, ge=2000, le=2100)


class FieldType(Enum):
    GoableSustainabilityIndex = "GoableSustainabilityIndex"


class Period(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    from_: AwareDatetime = Field(..., alias="from")
    to: AwareDatetime


class Weights(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    carbonNeutralShare: float
    electrificationShare: float


class Methodology(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    indexFormula: str
    weights: Weights
    suppression: str
    notes: str


class Overall(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    index: float = Field(..., ge=0.0, le=100.0)
    totalSessions: int = Field(..., ge=0)
    carbonNeutralSessions: int = Field(..., ge=0)
    carbonPositiveSessions: int = Field(..., ge=0)
    carbonNeutralShare: float = Field(..., ge=0.0, le=1.0)
    zonesReleased: int = Field(..., ge=0)
    zonesSuppressed: int = Field(..., ge=0)


class Zone(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    zoneKey: str
    label: str | None
    centroid: GeoPoint | None
    totalSessions: int = Field(..., ge=0)
    carbonNeutralShare: float = Field(..., ge=0.0, le=1.0)
    electrificationShare: float | None = Field(..., ge=0.0, le=1.0)
    seasonalConcentration: float | None = Field(..., ge=0.0, le=1.0)
    zoneIndex: float = Field(..., ge=0.0, le=100.0)


class License(Enum):
    CC_BY_4_0 = "CC BY 4.0"


class Publication(BaseModel):
    """
    Signing/publication metadata for the frozen report. null when no report has been published for this period (the honest empty-state) — every other field above is then a zero-data placeholder, not a real figure.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    year: int
    revision: int = Field(..., ge=1)
    publishedAt: AwareDatetime
    signedBy: str
    methodologyVersion: str


class V1PublicSustainabilityIndexGetResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    field_context: str = Field(..., alias="@context", examples=["https://schema.org"])
    field_type: FieldType = Field(..., alias="@type")
    generatedAt: AwareDatetime
    period: Period
    methodology: Methodology
    overall: Overall
    zones: list[Zone]
    license: License
    attribution: str
    publication: Publication | None = Field(
        ...,
        description="Signing/publication metadata for the frozen report. null when no report has been published for this period (the honest empty-state) — every other field above is then a zero-data placeholder, not a real figure.",
    )


class V1ResearchVerificationExportGetParametersQuery(BaseModel):
    from_: AwareDatetime | None = Field(None, alias="from")
    to: AwareDatetime | None = None


class Totals(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    activities: int
    subSpots: int
    clusters: int
    regions: int
    countries: int


class Family(Enum):
    water = "water"
    snow = "snow"
    air = "air"
    land = "land"


class Cluster(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    slug: str | None = None
    displayName: str | None = None
    countryCode: str | None = None
    subSpotCount: int | None = None


class Status4(Enum):
    """
    seeded ≥10 sub-spots · partial 1-9 · empty 0
    """

    seeded = "seeded"
    partial = "partial"
    empty = "empty"


class ByActivityItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    slug: str | None = None
    family: Family | None = None
    displayName: str | None = None
    subSpotCount: int | None = None
    clusterCount: int | None = None
    countryCount: int | None = None
    countries: list[str] | None = None
    clusters: list[Cluster] | None = None
    status: Status4 | None = Field(None, description="seeded ≥10 sub-spots · partial 1-9 · empty 0")
    lastUpdatedAt: AwareDatetime | None = Field(
        None,
        description="Newest commit touching the activity dir (null when no sub-spots yet)",
    )


class V1PublicCatalogStatsGetResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    computedAt: AwareDatetime = Field(..., description="ISO timestamp the bundled JSON was computed at")
    catalogVersion: str = Field(..., description="Catalog package version (mirrors package.json)")
    totals: Totals
    byActivity: list[ByActivityItem] = Field(
        ..., description="One entry per base profile, sorted DESC by subSpotCount."
    )


class EquipmentType(Enum):
    """
    Stream G equipment-transition signal.
    """

    electric = "electric"
    combustion = "combustion"
    manual = "manual"


class ReasonCategory1(Enum):
    """
    Structured cause when a session did not run as planned. Only 'weather' and 'safety' outcomes count as evidence against the forecast score and feed weather-suitability calibration; 'operational', 'customer_demand', 'mechanical', and 'unknown' are treated as business facts and excluded.
    """

    weather = "weather"
    operational = "operational"
    customer_demand = "customer_demand"
    safety = "safety"
    mechanical = "mechanical"
    unknown = "unknown"


class FacilityRenewableEnergy(Enum):
    """
    Operator annual declaration of the facility's energy source.
    """

    renewable = "renewable"
    mixed = "mixed"
    grid = "grid"
    unknown = "unknown"


class AccessMode(Enum):
    """
    How participants got to the session. Highest-materiality but lowest-substantiability signal (an operator estimate) — reported as an estimate, not a measured value.
    """

    foot = "foot"
    bike = "bike"
    public_transport = "public_transport"
    car = "car"
    boat = "boat"
    flight = "flight"
    mixed = "mixed"
    unknown = "unknown"


class EquipmentProvenance(Enum):
    """
    Whether the equipment used was rented/shared, owned, or a mix (circularity proxy).
    """

    rental_shared = "rental_shared"
    owned = "owned"
    mixed = "mixed"
    unknown = "unknown"


class V1OutcomesPostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    occurred_at: AwareDatetime
    activity_slug: str = Field(..., min_length=1)
    outcome_type: OutcomeType
    spot_id: str | None = Field(None, description="Optional catalogue sub-spot slug.")
    audit_log_id: str | None = Field(
        None,
        description="Optional link back to a scored session — pass a `session_id` from a POST /v1/score response. It is verified against `scoring_audit_log` before persist: an id resolving to no scored session (e.g. a /v1/score/multi or /v1/score/series session_id, which never write an audit row) is rejected 404 AUDIT_LOG_NOT_FOUND rather than silently persisted as an orphan the verification MV drops. Omit it for an un-sessioned outcome.",
    )
    detail: dict[str, Any] | None = None
    equipment_type: EquipmentType | None = Field(None, description="Stream G equipment-transition signal.")
    reason_category: ReasonCategory1 | None = Field(
        None,
        description="Structured cause when a session did not run as planned. Only 'weather' and 'safety' outcomes count as evidence against the forecast score and feed weather-suitability calibration; 'operational', 'customer_demand', 'mechanical', and 'unknown' are treated as business facts and excluded.",
    )
    group_size: int | None = Field(
        None,
        description="Participants in the session. Captured and disclosed (e.g. average group size) but held out of the sustainability composite pending a site carrying-capacity baseline.",
        ge=1,
    )
    facility_renewable_energy: FacilityRenewableEnergy | None = Field(
        None, description="Operator annual declaration of the facility's energy source."
    )
    access_mode: AccessMode | None = Field(
        None,
        description="How participants got to the session. Highest-materiality but lowest-substantiability signal (an operator estimate) — reported as an estimate, not a measured value.",
    )
    equipment_provenance: EquipmentProvenance | None = Field(
        None,
        description="Whether the equipment used was rented/shared, owned, or a mix (circularity proxy).",
    )
    batch_ref: str | None = Field(
        None,
        description="Client-supplied lot / ingestion-run handle. Tag a batch of outcomes with a shared value so a later POST /v1/outcomes/void can recall exactly that lot if it was mislabelled.",
        max_length=200,
        min_length=1,
    )


class V1OutcomesPostResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class OutcomeType2(Enum):
    """
    Narrow the recall to a single outcome_type.
    """

    ran = "ran"
    cancelled = "cancelled"
    rescheduled = "rescheduled"
    no_show = "no_show"
    note = "note"


class ReasonCategory2(Enum):
    """
    Narrow the recall to a single reason_category — e.g. void only the rows a dev mislabelled 'weather'.
    """

    weather = "weather"
    operational = "operational"
    customer_demand = "customer_demand"
    safety = "safety"
    mechanical = "mechanical"
    unknown = "unknown"


class V1OutcomesVoidPostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    reason: str = Field(
        ...,
        description="Why the lot is being recalled — recorded on every voided row for audit.",
        max_length=500,
        min_length=1,
    )
    batch_ref: str | None = Field(
        None, description="Recall the lot tagged with this batch_ref.", min_length=1
    )
    audit_log_id: str | None = Field(
        None, description="Recall the single outcome linked to this scored session."
    )
    submitted_by_key_id: str | None = Field(
        None,
        description="Recall everything a given API key submitted (combine with occurred_from/to).",
    )
    occurred_from: AwareDatetime | None = None
    occurred_to: AwareDatetime | None = None
    outcome_type: OutcomeType2 | None = Field(None, description="Narrow the recall to a single outcome_type.")
    reason_category: ReasonCategory2 | None = Field(
        None,
        description="Narrow the recall to a single reason_category — e.g. void only the rows a dev mislabelled 'weather'.",
    )


class V1OutcomesVoidPostResponse(BaseModel):
    voided: int


class Format(Enum):
    csv = "csv"
    json = "json"


class V1AuditExportGetParametersQuery(BaseModel):
    from_: AwareDatetime = Field(..., alias="from")
    to: AwareDatetime
    format: Format | None = "json"
    limit: int | None = Field(None, ge=1, le=5000)
    offset: int | None = Field(None, ge=0)


class Window(BaseModel):
    from_: str | None = Field(None, alias="from")
    to: str | None = None


class Meta(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    total: int
    limit: int
    offset: int
    window: Window


class V1AuditExportGetResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    rows: list[dict[str, Any]]
    meta: Meta


class Document(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID
    kind: str
    version: str
    title: str
    body: str
    contentHash: str
    status: str
    createdAt: AwareDatetime
    publishedAt: AwareDatetime | None


class V1LegalKindCurrentGetResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    document: Document


class ScoreResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    session_id: UUID = Field(
        ...,
        description="Stable id for this scored session (the `scoring_audit_log` row). Returned on every /v1/score response. Pass it back as `audit_log_id` on POST /v1/outcomes (or as the `:id` on POST /v1/score/:id/outcome) to link the observed outcome to this exact forecast, closing the calibration loop.",
    )
    score: float = Field(..., ge=0.0, le=100.0)
    verdict: Verdict
    confidence: float = Field(
        ...,
        description="How much to trust this `score` — a [0,1] multiplicative product of `forecast_skill` × `provider_agreement` × `profile_maturity` × `hierarchical_calibration` × `coverage` (see `confidenceDetail` for the individual factors). It is HORIZON- and CALIBRATION-sensitive:\n\n- `forecast_skill` now DECAYS with forecast lead time (the gap between issuance and the scored target time), the way operational NWP skill degrades: nowcast ≈ 0.90, ~0.78 at 24h, ~0.69 at 72h, ~0.60 at 7 days, ~0.51 at the ~16-day forecast limit. A near-term verdict therefore carries HIGHER confidence than a far-out one for the same spot. (This is a cold-start prior keyed on lead time, NOT yet a measurement of per-stratum skill — it is superseded factor-for-factor once measured skill is wired.)\n- `provider_agreement` defaults to 1.0 for the single-provider case: there is no penalty for the mere absence of a second opinion. A value < 1.0 appears only when ≥2 consensus constituents actually returned samples and diverged.\n- `profile_maturity` reflects catalog maturity (provisional 0.75 → reviewed 0.85 → calibrated 0.95) and RISES as a profile is outcome-calibrated.\n\nNOTE — intentional output shift: because `forecast_skill` decays with horizon and the cold-start factors were raised, `confidence` values differ from earlier releases. A near-term score now sits around ~0.55–0.62 (not the old ~0.41 flat baseline), and far-out scores read lower than near-term ones for the same location. This supersedes the previous documentation that described confidence as flat / independent of horizon / non-decaying. If you display or threshold on `confidence`, re-check your thresholds.",
        ge=0.0,
        le=1.0,
    )
    scoreBasis: ScoreBasis = Field(
        ...,
        description="Explicit discriminator for why `score`/`verdict` came out the way they did. 'forecast' = the normal path, every profile gate passed. 'gated' = a hard gate (safety or feasibility) tripped — `score` is forced to 0, but `breakdown`/`physics` still carry the real per-dimension conditions (each breakdown entry's `contribution` is zeroed, since nothing contributed to the gated 0, while `suitability`/`hasData` and the physics values stay populated) so a no-go response shows WHY. 'no_data' = no weather samples were available at all, so `breakdown`/`physics` are genuinely empty. Do not infer gate/no-data from `breakdown` emptiness — a gate trip populates `breakdown` too; read this field instead.",
    )
    breakdown: list[BreakdownItem]
    physics: dict[str, Any]
    alerts: list[Alert]
    eco: dict[str, Any]
    distribution: dict[str, Any] | None = Field(None, description="Present on ensemble requests")
    confidenceDetail: ConfidenceDetailForecast | None = None
    calibration_provenance: CalibrationProvenance | None = None
    assimilation: dict[str, Any] | None = None


class ConfidenceDetail(
    RootModel[ConfidenceDetailForecast | ConfidenceDetailHistorical | ConfidenceDetailClimate]
):
    root: ConfidenceDetailForecast | ConfidenceDetailHistorical | ConfidenceDetailClimate = Field(
        ..., discriminator="mode"
    )


class V1IntelligenceExplainPostRequest(BaseModel):
    """
    Provide exactly one of scoreResult or session_id.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    location: GeoPoint
    scoreResult: ScoreResponse | None = None
    session_id: UUID | None = None
    locale: Locale | None = None
    model: Model1 | None = None


class V1IntelligenceEdgeCasePostRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    location: GeoPoint
    scoreResult: ScoreResponse | None = None
    session_id: UUID | None = None
    locale: Locale | None = None
    model: Model1 | None = None
